Fs imp
IGinX-THU/IGinX pull request #110
Opened 2023-07-29 04:30 UTC by RemHero

设计文档参考
https://oxlh5mrwi0.feishu.cn/docx/K2vydNUnyo0lxtxNYfgcM661n2c

2023-08-09 08:48 UTC, SolomonAnn commented on conf/config.properties
> +#storageEngineList=127.0.0.1#4860#filesystem#has_data=false#is_read_only=false
端口设置成4860有什么特殊用处吗？如果没有的话，改成6667，和parquet统一

2023-08-09 08:53 UTC, SolomonAnn commented on conf/config.properties
> +mountedDirectory=dataSources/filesystem/src/test/java/cn/edu/tsinghua/iginx/storage/
这个目录不存在，还不如写成/path/to/your/filesystem，也就是必须让用户指定

2023-08-09 08:54 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
> +  private String mountedDirectory = "";
填充默认值

2023-08-09 08:59 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/Value.java
> +    if (binaryV != null) {
什么情况下binaryV是null？出现这种情况是合理的吗？还是使用上出错了？

2023-08-09 09:06 UTC, SolomonAnn commented on dataSources/filesystem/pom.xml
> +            <groupId>com.bpodgursky</groupId>
引入的4个依赖移除后仍然能正常编译，确认一下是否真的需要；以及，把iginx-core移到最前面，和其他pom统一

2023-08-09 09:23 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/FileSystemStorage.java
> +  ExecutorService executorService = Executors.newFixedThreadPool(1); // 为了更好的管理线程
数量为1的话就用newSingleThreadExecutor

2023-08-09 09:23 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/FileSystemStorage.java
> +  ExecutorService executorService = Executors.newFixedThreadPool(1); // 为了更好的管理线程
”更好地“

2023-08-09 09:32 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/FileSystemStorage.java
> +    String argRoot = meta.getExtraParams().get("dir");
storageEngineList里还能配置dir？这个dir和挂载目录的区别是？

2023-08-09 09:33 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/FileSystemStorage.java
> +    this.executor = new LocalExecutor(root);
没必要加this

2023-08-09 09:37 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/Executor.java
> +  List<Column> getColumnOfStorageUnit(String storageUnit) throws PhysicalException;
改成getColumnsOfStorageUnit吧

2023-08-09 09:39 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/LocalExecutor.java
> +      logger.error("root should not to be null!");
没有”to“

2023-08-09 09:41 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/LocalExecutor.java
> +        logger.warn("dummy storage query should contain no tag filter");
用中文表述吧，英文不通顺

2023-08-09 09:44 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/LocalExecutor.java
> +  public TaskExecuteResult executeQueryTask(
本文件的series都改成paths，没有特殊情况的话形参和实参名字保持一致，方便阅读

2023-08-09 10:06 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/query/entity/Record.java
> +  private DataType dataType;
为什么不直接用已有的Value类？

2023-08-09 10:08 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/query/entity/FileSystemResultTable.java
> +  private List<Record> val;
val重命名成records

2023-08-09 10:18 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/server/FileSystemServer.java
> +    logger.info("Filesystem service starts successfully!");
报错信息和run函数里不一致

2023-08-09 10:22 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/ConfLoader.java
> +    String rowRootPath = config.getMountedDirectory();
row在这里的含义是？

2023-08-10 01:51 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/FilterTransformer.java
> +  //  private static int index = 0;
删掉

2023-08-10 01:51 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/FilterTransformer.java
> +    return new String(JSONB.toBytes(filter, JSONWriter.Feature.WriteClassName));
为什么要WriteClassName?

2023-08-10 02:43 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/FilterTransformer.java
> +import com.alibaba.fastjson2.JSONB;
使用JSONB，不使用JSON的原因是？而且，toString和toFilter方法好像并没有用到

2023-08-10 02:53 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/FileSystemStorage.java
> +        FilterTransformer.toFSFilter(filter),
调用thrift接口时再做转换

2023-08-10 02:57 UTC, SolomonAnn commented on test/src/test/resources/testConfig.properties
> +FileSystem=127.0.0.1#6667#filesystem
加上has_data和is_read_only

2023-08-10 03:04 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/utils/SQLTestTools.java
> +      logger.info("check the pathList {}", pathList);
删掉调试日志

2023-08-10 03:04 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/utils/SQLTestTools.java
> +  private static void compareStirngValue(String expectedValue, String actualValue) {
这个函数和assertEquals没区别吧，assertEquals出错也会打印错误信息

2023-08-10 03:10 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/FileSystemCapacityExpansionIT.java
> +      statement.append(", dir:");
dir在extraParams里，没必要重写这个函数

2023-08-10 03:11 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/FileSystemCapacityExpansionIT.java
> +    super(filesystem, "username:root, password:root, sessionPoolSize:20", 4860, 4861, 4862);
不需要sessionPoolSize这个参数，端口也得和config文件保持一致

2023-08-10 03:14 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/FileSystemCapacityExpansionIT.java
> +    EXP_DATA_TYPE_LIST = Arrays.asList(DataType.BINARY, DataType.BINARY);
为什么要改成binary？以及为什么在FileSystemHistoryDataGenerator里改了之后，这里又要改？

2023-08-10 03:19 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> -
没必要删，留着吧

2023-08-10 03:23 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/DataTypeUtils.java
> +  public static Object parseStringByDataTyp(String val, DataType type) {
在Record里添加Value之后这个方法就不需要了

2023-08-10 03:26 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/JsonUtils.java
> +  public static Map<String, String> transformToSS(String content) {
改个更加直观的函数名

2023-08-10 03:29 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/JsonUtils.java
> +    if (content == null || content.equals("{}")) {
parseObject也能解析{}

2023-08-10 03:30 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/JsonUtils.java
> +    if (content == null || content.equals("{}")) {
从外层判断content是否为空

2023-08-10 03:30 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +  public static List<String> splitAround(String expr, int left, int right, String separator) {
没有用到的函数

2023-08-10 03:34 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FileMeta.java
> +  public static final long IGINX_FILE_META_INDEX = 10L;
因为现在只有2行，所以先设置成2行，后面如果有需要再增加

2023-08-10 03:44 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/TagKVUtils.java
> +  public static boolean match(Map<String, String> tags, TagFilter tagFilter) {
和core下面的TagKVUtils完全一样的函数，就不要再复制一遍了

2023-08-10 06:39 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/query/entity/FileSystemResultTable.java
> +  public FileSystemResultTable(File file, List<Record> val) {
本文件的val都改成records

2023-08-10 06:40 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/server/FileSystemWorker.java
> +  private static final Status GET_COLUMNS_FAIL = new Status(404, "get key series fail");
key series？？？仔细检查一下

2023-08-10 06:44 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/server/FileSystemWorker.java
> +      List<Column> tsList = executor.getColumnsOfStorageUnit(storageUnit);
tsList改成columns

2023-08-10 06:45 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/server/FileSystemWorker.java
> +          columns -> {
columns改成column

2023-08-10 06:54 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FileMeta.java
> +  private Map<String, String> tag;
tag改成tags

2023-08-10 06:55 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FileMeta.java
> +  public boolean ifTagEqual(Map<String, String> map) {
ifTagEqual和ifContainTag均未用到

2023-08-10 07:04 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/controller/Controller.java
> +  private static String WILDCARD = FilePath.WILDCARD;
直接用FilePath.WILDCARD就行了，没必要再重复定义一个变量

2023-08-10 07:05 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/controller/Controller.java
> +    FilePath.setSeparator(System.getProperty("file.separator"));
SEPARATOR在FilePath类里已经被赋值了，直接使用即可

2023-08-10 07:07 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FilePath.java
> +  public static void setSeparator(String SEPARATOR) {
静态变量不应有set和get方法

2023-08-10 07:09 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FilePath.java
> +  private String oriSeries;
这个文件里出现的series统一改成path，和其他文件统一

2023-08-10 07:20 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FilePath.java
> +  private String fileName;
这个类本质上是个工具类，而不是实体类

2023-08-10 07:23 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/entity/FileType.java
> +    } else if (fileName.endsWith(".txt")) {
只支持txt文件？判断是否为IGINX_FILE也不能通过文件名是否包含.iginx，参考parquet的magic number

2023-08-10 07:32 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +  public List<Record> readDir(File file) throws IOException {
为什么返回一个空列表？

2023-08-10 08:24 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +            writer.write("\n");
writer.newLine()

2023-08-10 08:25 UTC, SolomonAnn commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +            writer.write(line);
缓冲区积累到一定程度需要flush

2023-08-19 06:01 UTC, zhuyuqing requested changes

2023-08-19 06:01 UTC, zhuyuqing commented on test/src/test/resources/testConfig.properties
> +FileSystem=127.0.0.1#6667#filesystem#has_data=false#is_read_only=false
是不是应该允许用户配置数据所在目录？配置应该放这里吧？

2023-08-20 02:18 UTC, zhuyuqing requested changes

2023-08-20 02:18 UTC, zhuyuqing commented on conf/config.properties
> +#storageEngineList=127.0.0.1#6667#filesystem#dir=/path/to/your/filesystem#has_data=false#is_read_only=false
配置再增加一个吧，到底1个Value是多少字节的数据

2023-09-01 01:51 UTC, merged