hotfix(postgresql): change separator
IGinX-THU/IGinX pull request #123
Opened 2023-08-25 07:53 UTC by Yihao-Xu

Now the separator of postgresql has been changed.
A column name like "us.d1.s1{t1=v1,t2=v2}" will be stored in pg as "us.d1.s1-t1=v1-t2=v2".

2023-08-25 08:40 UTC, zhuyuqing requested changes

2023-08-25 08:40 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +  public static final char SEPARATOR = '.';
别的数据也要拼，拎一个全局变量出来（有可能已经存在）

2023-08-25 08:40 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/ExprUtils.java
>        regexPattern = regexPattern.replace(".", "\\.");
这段可能会非常慢，
可以写得更高效一点

2023-08-25 08:40 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> -  public static final String KEY_NAME = "\u2E85";
TAG_KEY TAG_VALUE的中文字符也相应处理一下吧

2023-08-29 01:17 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/ExprUtils.java
>        regexPattern = regexPattern.replace(".", "\\.");
已经改成regexPattern = regexPattern.replace("[.$^{}]", "\\\\$0")一次性替换全部字符以提升速度

2023-08-29 01:17 UTC, Yihao-Xu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> -  public static final String KEY_NAME = "\u2E85";
已处理

2023-08-29 01:18 UTC, Yihao-Xu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +  public static final char SEPARATOR = '.';
已放到share中

2023-08-30 01:22 UTC, SolomonAnn approved these changes

2023-08-31 01:48 UTC, merged