test union
IGinX-THU/IGinX pull request #13
Opened 2023-02-18 04:50 UTC by RemHero

2023-02-20 02:05 UTC, YouJiacheng approved these changes

2023-02-20 03:01 UTC, Cauchy-NY approved these changes

2023-02-20 09:44 UTC, zhuyuqing requested changes
Please fix all comments sent to you. Thanks.

2023-02-21 15:38 UTC, YouJiacheng commented on .github/workflows/IoTDB-CE.yml
> +        if: always()
Can we use check `matrix.DB-name` here?

2023-02-21 15:44 UTC, YouJiacheng commented on .github/workflows/IoTDB-CE.yml
> +        if: always()
Can we check `matrix.DB-name` here?

2023-02-21 15:44 UTC, YouJiacheng commented on .github/workflows/IoTDB-CE.yml
> +      - name: Prepare CapExp environment
Duplicated name?

2023-02-21 15:44 UTC, YouJiacheng commented on .github/workflows/IoTDB-CE.yml
> +      - name: Prepare CapExp environment
Maybe "Prepare CapExp environment for oriNoDataExpNoData"

2023-02-21 15:44 UTC, YouJiacheng commented on .github/workflows/IoTDB-CE.yml
> +      #第 2 阶段测试开始==========================================
Does "oriNoDataExpNoData IT" depend on "oriHasDataExpHasData IT"? Maybe we can run them in parallel to reduce feedback time.

2023-02-23 06:38 UTC, closed without merging