fix udf path
IGinX-THU/IGinX pull request #136
Opened 2023-09-08 17:05 UTC by shinyano

make udf path flexible based on env "IGINX_HOME"

2023-09-09 02:58 UTC, zhuyuqing requested changes

2023-09-09 02:58 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +          System.getenv().getOrDefault(Constants.IGINX_HOME, System.getProperty("user.dir")),
在windows上环境变量不好配置，config文件里配置吧。

2023-09-09 02:58 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
> +            EnvUtils.loadEnv(Constants.UDF_LIST, iginxHome + "/" + Constants.UDF_LIST_FILE))) {
UDF必须放到IGinX根目录下吗

2023-09-09 02:59 UTC, zhuyuqing requested changes
请相应加上测试。

2023-09-12 11:58 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +          System.getenv().getOrDefault(Constants.IGINX_HOME, System.getProperty("user.dir")),
已修改为config参数

2023-09-12 11:59 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
> +            EnvUtils.loadEnv(Constants.UDF_LIST, iginxHome + "/" + Constants.UDF_LIST_FILE))) {
已改为UDF文件相对目录可在config中进行配置

2023-09-18 01:59 UTC, SolomonAnn commented on .github/workflows/standalone-test.yml
> +            - name: Start IGinX
只启动一次iginx，后面的单机测试会报错吗？

2023-09-18 02:08 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/FileUtils.java
> +      return true;
return false吧

2023-09-18 02:10 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
> +      config.setIginxHomePath(
iginxHomePath好像是个临时变量，只在这里用到了？如果是的话，就不需要在Config.java声明了

2023-09-18 14:45 UTC, shinyano commented on .github/workflows/standalone-test.yml
> +            - name: Start IGinX
会超时，暂时不修改

2023-09-18 14:46 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
> +      config.setIginxHomePath(
只在这里用了一次，已改为局部变量

2023-09-19 07:27 UTC, SolomonAnn approved these changes

2023-09-22 01:34 UTC, zhuyuqing approved these changes

2023-09-22 01:34 UTC, merged