feat: udf support args
IGinX-THU/IGinX pull request #172
Opened 2023-10-18 08:12 UTC by Cauchy-NY

2023-10-26 09:20 UTC, SolomonAnn approved these changes

2023-10-26 12:59 UTC, jzl18thu requested changes

2023-10-27 01:19 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      columns.add(pathContext.getText());
done

2023-10-27 01:52 UTC, jzl18thu approved these changes

2023-10-27 08:47 UTC, zhuyuqing requested changes

2023-10-27 08:47 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +  public void testUDFWithArgs() {
增加列与UDF混合在一起被选出的测试用例

2023-10-27 08:52 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +  public void testUDFWithArgs() {
done

2023-10-28 04:08 UTC, zhuyuqing approved these changes

2023-10-28 04:09 UTC, merged