fix(parquet&fs): add dir name to data column as prefix
IGinX-THU/IGinX pull request #177
Opened 2023-10-20 02:08 UTC by shinyano

将dummy文件路径最后一级从schema_prefix改为手动添加到列名前缀
### 系统
IGinX启动时 & add storage时逻辑修改，不改动schema_prefix

### parquet & fs

2023-10-27 08:43 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +        logger.error(
参考其他日志打印的做法，logger打印日志不需要format，用{}代替%s即可

2023-10-27 09:35 UTC, SolomonAnn approved these changes

2023-10-28 03:18 UTC, zhuyuqing requested changes

2023-10-28 03:18 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> +                new Pair<>("C:\\", validDummyPath),
actions里没有windows测试环境，为啥可以有这个C:\目录作为测试？

2023-10-28 03:18 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> +                new Pair<>("C:\\", validDummyPath),
是不是应当单独搞一个windows测试环境，来测试一下？

2023-11-04 02:50 UTC, zhuyuqing requested changes

2023-11-04 02:50 UTC, zhuyuqing commented on .github/workflows/unit-test.yml
> +                os: [ubuntu-latest, macos-latest, windows-latest]
这个只在parquet上测试了？文件 系统上也在测试吧？要不不完整啊

2023-11-04 02:50 UTC, zhuyuqing commented on .github/workflows/unit-test.yml
> +                os: [ubuntu-latest, macos-latest, windows-latest]
UT只在core里，所以跟Parquet或文件系统都 没关系？所以，最后这句mvn clean package -pl dataSources/parquet -am -P-format -q
在干啥？

2023-11-06 01:15 UTC, zhuyuqing approved these changes

2023-11-06 01:18 UTC, merged