feat: SQL support backquote
IGinX-THU/IGinX pull request #178
Opened 2023-10-20 03:46 UTC by jzl18thu

2023-10-21 09:44 UTC, Cauchy-NY requested changes

2023-10-21 09:44 UTC, Cauchy-NY commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
>     : nodeName (DOT nodeName)*
nodeName 在语法层面任然可以是一个纯数字

2023-10-23 02:49 UTC, jzl18thu commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
>     : nodeName (DOT nodeName)*
所有 constant 均从 nodeName 中移除

2023-10-25 01:32 UTC, Cauchy-NY approved these changes
LGTM

2023-10-25 01:36 UTC, SolomonAnn approved these changes

2023-10-25 01:38 UTC, merged