feat: "and comparison operator" & "or comparison operator"
IGinX-THU/IGinX pull request #180
Opened 2023-10-20 07:51 UTC by jzl18thu

2023-10-27 09:51 UTC, SolomonAnn commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/FilterTransformer.java
> +    String regex_symbol = isLikeOp(filter.getOp()) ? "$" : "";
统一用驼峰式命名

2023-10-27 09:58 UTC, SolomonAnn commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/FilterTransformer.java
> +    if (op.startsWith("&")) {
如果是startsWith("|")需不需要去掉|，iotdb去掉了

2023-10-27 10:00 UTC, SolomonAnn commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/tools/FilterTransformer.java
> +  private static String op2StrWithoutAnd(Op op) {
这个函数需要和iotdb的op2StrWithoutAndOr函数统一吗

2023-10-30 01:50 UTC, Cauchy-NY requested changes

2023-10-30 01:50 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +    query = "SELECT s1 FROM us.* WHERE s1 &> 200 and s1 &< 210;";
覆盖的情况不全，对于and or比较符的不同组合情况，多加一些测试

2023-10-30 02:17 UTC, jzl18thu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/FilterTransformer.java
> +    String regex_symbol = isLikeOp(filter.getOp()) ? "$" : "";
done

2023-10-30 02:38 UTC, jzl18thu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +    query = "SELECT s1 FROM us.* WHERE s1 &> 200 and s1 &< 210;";
done

2023-10-30 02:39 UTC, Cauchy-NY approved these changes
LGTM

2023-10-30 02:52 UTC, Yihao-Xu commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/tools/FilterTransformer.java
> +  private static String op2StrWithoutAnd(Op op) {
已统一，统一后的函数放置在Op.java中

2023-10-30 02:52 UTC, Yihao-Xu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/FilterTransformer.java
> +    if (op.startsWith("&")) {
统一改为了不需要去掉，因为目前的op2Str，`&<`会转换为`&<`，但`|<`会直接默认转换成`<`

2023-10-30 03:58 UTC, SolomonAnn approved these changes

2023-10-31 01:26 UTC, merged