query result with repeating key throw warning
IGinX-THU/IGinX pull request #181
Opened 2023-10-25 08:58 UTC by RemHero

2023-10-26 03:10 UTC, Cauchy-NY requested changes

2023-10-26 03:10 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/PhysicalEngine.java
> +  default RowStream execute(RequestContext ctx, Operator root, OperatorContext context)
这里有两个问题
1. 两个Context显然用具体的aContext和bContext命名要比一个context一个ctx明确
2. 既然context是上下文，那么在你的实现里面是一个统一的大的上下文还是两个阶段的上下文，如果是前者，为什么不考虑复用已有的上下文，如果是后者，为什么这里会同时出现

2023-10-26 03:10 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/optimizer/PhysicalOptimizer.java
> +  default PhysicalTask optimize(Operator root, OperatorContext context) {
第二个入参在Default实现没有用到的话，不满足接口最小化原则

2023-10-26 03:10 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/context/OperatorContext.java
> +package cn.edu.tsinghua.iginx.engine.shared.operator.context;
operator 这个目录是逻辑层和物理层共用的，而这个ctx只是执行时的ctx，因此这并不适合放在这块
直接放在shared或是和所有ctx一起放在shared/context下都是合理的

2023-10-27 02:56 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/ContextWarningMsgType.java
> +  SameKeyWarning,
这个在目前看来没有枚举的必要，你无法肯定后续的分类一定是按照context warning来的

2023-10-27 03:03 UTC, Cauchy-NY requested changes

2023-10-27 03:03 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
> +    boolean isConflictInKey = false;
isConflictInKey 好像没有看到使用的地方

2023-10-27 03:03 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
> +      Table table = new Table(newHeader, newRows);
这一段没看出来作用。。。

2023-10-30 09:00 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/StatementExecutor.java
> +    status.setMessage(ctx.getWarningMsg());
这里为什么不用判断ctx.getWarningMsg() != null && !ctx.getWarningMsg().isEmpty()

2023-10-30 09:29 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
> +        context = tableB.getContext();
tableA

2023-10-30 09:29 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
> +        context = tableA.getContext();
tableB

2023-10-30 09:30 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
> +        context.setWarningMsg(
修改message，并和其他地方统一

2023-10-30 09:36 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> +      if ((res.getWarningMsg() == null || res.getWarningMsg().isEmpty())
比较warningMsg的值是否等于设置的报错语句

2023-10-30 09:45 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/OperatorMemoryExecutor.java
>    RowStream executeUnaryOperator(UnaryOperator operator, RowStream stream) throws PhysicalException;
没用到的接口

2023-10-30 09:45 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/OperatorMemoryExecutor.java
>    RowStream executeBinaryOperator(BinaryOperator operator, RowStream streamA, RowStream streamB)
没用到的接口

2023-10-30 09:46 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/Result.java
> +    status.setMessage(null);
建议把重叠key作为partial_success返回

2023-10-31 09:27 UTC, SolomonAnn approved these changes

2023-11-01 02:38 UTC, Cauchy-NY approved these changes

2023-11-01 03:26 UTC, merged