feat(zeppelin): zeppelin download files
IGinX-THU/IGinX pull request #192
Opened 2023-11-10 08:50 UTC by Yihao-Xu

实现了zeppelin下载文件的功能，当输入outfile语句时，zeppelin将文件下载到服务器上暂存，并提供下载链接。
详见https://oxlh5mrwi0.feishu.cn/docx/RcDhdsC0kovZPexxLTechKWOnZb

2023-11-13 01:50 UTC, SolomonAnn commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter.java
> +  private static final String DEFAULT_OUTFILE_DIR = "/home/xyh/code/zeppelin_outfile_dir/";
默认值不能是真实路径

2023-11-13 02:00 UTC, SolomonAnn commented on zeppelin-interpreter/src/main/resources/interpreter-setting.json
> +        "defaultValue": "/home/xyh/code/zeppelin_outfile_dir/",
默认值不能是真实路径

2023-11-22 02:20 UTC, Yihao-Xu commented on zeppelin-interpreter/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter.java
> +  private static final String DEFAULT_OUTFILE_DIR = "/home/xyh/code/zeppelin_outfile_dir/";
改了

2023-11-22 02:20 UTC, Yihao-Xu commented on zeppelin-interpreter/src/main/resources/interpreter-setting.json
> +        "defaultValue": "/home/xyh/code/zeppelin_outfile_dir/",
改了

2023-11-23 03:55 UTC, zhuyuqing requested changes
重构，以去除对NginX的依赖吧

2024-03-01 09:53 UTC, closed without merging