feat(udf): access key in UDSFs
IGinX-THU/IGinX pull request #193
Opened 2023-11-13 08:43 UTC by shinyano

传递key列给UDSF函数，处理后可以返回含有key或不含key的数据，但key列必须在所有数据列的最前面

To-Do：加入测试

2023-11-15 07:41 UTC, Cauchy-NY requested changes

2023-11-15 07:41 UTC, Cauchy-NY commented on udf_funcs/python_scripts/udsf_addOneDay.py
这些python文件统一用下划线命名

2023-11-15 07:41 UTC, Cauchy-NY commented on udf_funcs/python_scripts/udsf_addOneDay.py
btw，好像没有看到新增的udsf用在哪

2023-11-17 07:35 UTC, Cauchy-NY approved these changes

2023-11-20 02:10 UTC, SolomonAnn approved these changes

2023-11-20 02:11 UTC, merged