dataSource统一测试框架
IGinX-THU/IGinX pull request #199
Opened 2023-11-21 07:44 UTC by RemHero

2023-12-01 08:50 UTC, Cauchy-NY commented on .github/workflows/unit-test.yml
> +                  mvn clean package -pl dataSources/parquet -am -P-format -q -Pskip-tests
这里为啥要跳过测试

2023-12-01 08:54 UTC, Cauchy-NY requested changes
这个“统一测试框架”没有基于对接层接口进行完备的框架设计

2023-12-01 08:54 UTC, Cauchy-NY commented on .github/workflows/unit-test.yml
> +                  mvn clean package -pl dataSources/parquet -am -P-format -q -Pskip-tests
这里为啥要跳过测试

2023-12-01 08:54 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/datasource/DataSourceIT.java
> +        {
既然有个testConfig，为啥这块不写在配置里面呢

2023-12-08 01:07 UTC, SolomonAnn approved these changes

2023-12-11 08:02 UTC, SolomonAnn approved these changes

2023-12-11 08:36 UTC, Cauchy-NY reviewed
这个PR还是没有测试完整的对接层接口，按照yanzhe的意思可以在后续PR中完善

2023-12-11 08:36 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/datasource/DataSourceIT.java
> +  private final Map<String, String> NAME_TO_INSTANCE =
这个也可以抽成配置吧

2023-12-13 03:15 UTC, Cauchy-NY approved these changes

2023-12-13 09:58 UTC, merged