refract folded operator and explain
IGinX-THU/IGinX pull request #200
Opened 2023-11-22 02:27 UTC by Cauchy-NY

2023-11-22 09:41 UTC, jzl18thu approved these changes

2023-11-23 03:54 UTC, zhuyuqing requested changes

2023-11-23 03:54 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/Operator.java
>  public interface Operator {
减去的冗余operator是哪些？

2023-11-24 01:56 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/Operator.java
>  public interface Operator {
不是去除冗余的operator，而是folded重构之后，所有需要拓充的visitor可以少实现两个冗余接口

2023-11-24 09:30 UTC, merged