support cancel executing tasks
IGinX-THU/IGinX pull request #214
Opened 2023-12-07 09:05 UTC by Cauchy-NY

2023-12-13 02:22 UTC, SolomonAnn approved these changes

2023-12-13 07:49 UTC, zhuyuqing requested changes
加上cancel的测试吧

2023-12-15 18:33 UTC, Cauchy-NY commented
/bin/sh 不支持数组。。。。。

2023-12-18 02:23 UTC, zhuyuqing approved these changes

2023-12-18 12:48 UTC, merged