Increase Thrift Timeout
IGinX-THU/IGinX pull request #217
Opened 2023-12-12 08:28 UTC by RemHero

2023-12-15 01:49 UTC, zhuyuqing requested changes
增加add storageengine的相关参数

2023-12-15 07:22 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ThriftConnPool.java
> +        extraParams.containsKey("thrift_timeout")
改成getOrDefault

2023-12-15 10:21 UTC, SolomonAnn approved these changes

2023-12-18 01:38 UTC, zhuyuqing approved these changes

2023-12-18 01:39 UTC, merged