feat(Optimizer): implement filter fragment optimizer rbo
IGinX-THU/IGinX pull request #220
Opened 2023-12-15 17:29 UTC by Yihao-Xu

2023-12-28 02:58 UTC, Cauchy-NY requested changes

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
> +    try {
try-resource 机制建议保留

2023-12-28 02:58 UTC, Cauchy-NY commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +   | SET RULES stringLiteral (COMMA stringLiteral)* # setRulesStatement
确定的语法要素建议作为语句的一部分

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/FilterFragmentRule.java
> +      selectOperator.setSource(new OperatorSource(root));
建议使用call.transform();

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/RuleCollection.java
> +        banRulesByName(Collections.singletonList(ruleInfo[0]));
建议在循环中收集齐所有需要ban的rule，再统一调用banRulesByName，这样能节省内存分配开销

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/RuleCollection.java
> +    // 先检查是否有不存在的规则，再进行设置
统一下注释语言

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/MetaManagerMock.java
> +  private Map<ColumnsInterval, List<FragmentMeta>> getFragmentMapByColumnsIntervalMap =
getFragmentMapByColumnsIntervalMap 完全看不出成员变量的含义

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +              if (ruleChange.length != 2
这段解析按照之前的语法设计完全可以避免

2023-12-28 02:58 UTC, Cauchy-NY commented on core/src/test/java/cn/edu/tsinghua/iginx/optimizer/TreeBuilder.java
> +   * @return 一棵树
这条注释完全没有意义，建议大概描述一下树形

2023-12-28 03:03 UTC, RemHero approved these changes

2024-01-02 01:43 UTC, Cauchy-NY approved these changes

2024-01-02 08:04 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +OFF
这个关键词已经没用了？没用就去掉吧

2024-01-02 08:06 UTC, Yihao-Xu commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +OFF
有用的，现在是用 `set rules FilterFragmentRule=ON, RemoveNotRule=OFF; `这样的形式来设置rule的开关，需要用到OFF关键词。

2024-01-02 08:14 UTC, zhuyuqing requested changes

2024-01-02 08:14 UTC, zhuyuqing commented on conf/config.properties
> +ruleBasedOptimizer=RemoveNotRule=on,FilterFragmentRule=on
如果规则在代码库里，但是没有声明，现在是on，应当为off

2024-01-02 08:14 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +            + "+------------------+------+\n"
配合上面的config修改，一开始，仅添加一个，后面通过set rules来增加，这样可以将相关功能测试到位

2024-01-03 01:36 UTC, Yihao-Xu commented on conf/config.properties
> +ruleBasedOptimizer=RemoveNotRule=on,FilterFragmentRule=on
已修改

2024-01-03 01:36 UTC, SolomonAnn approved these changes

2024-01-03 01:36 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +            + "+------------------+------+\n"
已添加相应测试

2024-01-03 07:37 UTC, zhuyuqing approved these changes

2024-01-03 07:38 UTC, merged