dummy test
IGinX-THU/IGinX pull request #223
Opened 2023-12-22 07:01 UTC by RemHero

2023-12-25 09:19 UTC, Cauchy-NY requested changes
添加一些关于PR的简要说明吧

2023-12-25 09:19 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> +  private static final Map<String, String> NAME_TO_INSTANCE =
这些配置应该可以从代码里面抽出来吧，之前应该有过类似的逻辑

2023-12-25 09:19 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> +          put("FileSystem", false);
这些应该同样可以抽出来

2023-12-25 09:19 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/FileSystemHistoryDataGenerator.java
>      // 创建并写入文件
这注释为啥自己不同阶段还中英混杂

2023-12-27 06:49 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/FileReader.java
> +      logger.warn(String.format("Fail to find file, path=%s", filePath));
不要用format，改成占位符

2023-12-27 06:54 UTC, SolomonAnn commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/FileReader.java
> +      return null;
没看懂这里为什么需要提前返回null，以及这个函数的默认返回值为什么不设置成空字符串

2023-12-27 07:06 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/postgresql/PostgreSQLHistoryDataGenerator.java
> +          logger.info(
改成占位符

2023-12-27 07:13 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +    assertEquals(expected, actual);
assertEquals(Object expected, Object actual)，有这种用法，试试看行不行，行的话就把上面对于非字符串类型还需要单独判断的地方都删掉

2023-12-27 07:22 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/rest/RestIT.java
> +  private boolean dummyNoData = true;
不明白这个变量的含义，建议改名或者加注释

2024-01-24 08:25 UTC, Cauchy-NY requested changes

2024-01-24 08:25 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> +    if (!conf.isScaling() || !NEED_SEPARATE_WRITING.get(conf.getStorageType())) {
添加一些注释

2024-01-25 06:58 UTC, SolomonAnn approved these changes

2024-01-25 07:43 UTC, Cauchy-NY approved these changes

2024-01-26 02:35 UTC, SolomonAnn approved these changes

2024-01-26 02:46 UTC, merged