Better close session in test
IGinX-THU/IGinX pull request #225
Opened 2023-12-22 08:24 UTC by RemHero

处理了原有SQLSessionIT中部分测试没有关闭session的问题

2024-01-09 02:35 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/NewSessionIT.java
> +        logger.error("server session_id_list size is not equal to client session_id_list size.");
不通顺，建议写中文

2024-01-10 07:01 UTC, SolomonAnn approved these changes

2024-01-11 01:24 UTC, Cauchy-NY requested changes

2024-01-11 01:24 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/NewSessionIT.java
> +      if (existsSessionIDs.size() != sessionIDs.size()) {
既然这个条件和前面一个条件合起来是等价的话，为啥不重写整个测试逻辑呢

2024-01-11 07:25 UTC, Cauchy-NY approved these changes

2024-01-11 07:26 UTC, merged