refactor(logical): refactor QueryGenerator.java
IGinX-THU/IGinX pull request #237
Opened 2024-01-04 01:15 UTC by Yihao-Xu

重构了QueryGenerator.java，将generateRoot中对每个算子的构建逻辑提取成函数，优化可读性，减少重复代码。

2024-01-04 02:48 UTC, Cauchy-NY requested changes

2024-01-04 02:48 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
> +    if (!selectStatement.getFromParts().isEmpty()) {
提前返回

2024-01-04 02:48 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
> +    if (selectStatement.getSetOperator() == OperatorType.Intersect) {
提前返回

2024-01-04 02:48 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
> +    if (root == null && !metaManager.hasWritableStorageEngines()) {
抽成一个专门的checker吧

2024-01-04 02:48 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
> +  private Operator generateRoot(UnarySelectStatement selectStatement) {
添加一些大体的步骤描述

2024-01-05 08:43 UTC, Cauchy-NY approved these changes

2024-01-05 09:02 UTC, SolomonAnn approved these changes

2024-01-06 06:55 UTC, merged