refactor(logical): refactor UnarySelectStatement
IGinX-THU/IGinX pull request #242
Opened 2024-01-11 02:37 UTC by Yihao-Xu

2024-01-18 08:12 UTC, Cauchy-NY requested changes
两个pkg name改下吧
selectstatement -> select
selectstatementclause->subclause

2024-01-18 08:12 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      if (isHavingFilter) {
这部分破坏了内聚性，应该把相应的逻辑放在外面做

2024-01-18 08:12 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      if (isHavingFilter) {
这里也有同样的问题

2024-01-24 01:57 UTC, Cauchy-NY approved these changes

2024-01-24 08:54 UTC, SolomonAnn approved these changes

2024-01-25 06:46 UTC, merged