(enhance)Better Log Exception
IGinX-THU/IGinX pull request #247
Opened 2024-01-18 14:46 UTC by RemHero

2024-01-21 09:02 UTC, zhuyuqing requested changes

2024-01-21 09:02 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
> +                              result =
为啥这里把logging也去掉了？

2024-01-21 09:02 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/FilterUtils.java
> +        throw new IginxRuntimeException("Unexpected filter type: " + filter.getType());
为啥这里是IginXRuntimeException，但下面同样是执行层的却是PhysicalException？不太一致？

2024-02-29 02:31 UTC, Cauchy-NY reviewed
自定义Exception应该有个完整的层次化结构，例如最顶层的IGinXException直接继承Java的Exeception，他的子类异常可以按照层次划分，如ClientException、RestException、EngineException等，EngineException又可以被细化分为LogicalException、PhysicalException等

2024-02-29 02:49 UTC, zhuyuqing requested changes

2024-02-29 02:49 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/MemoryPhysicalTaskDispatcher.java
> +                                new PhysicalException("unexpected exception: " + e.getMessage()));
PhysicalException和PhysicalRuntimeException是怎么区分的？

2024-02-29 02:49 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/exceptions/IginxRuntimeException.java
> +/*
包的命名，不符合规范吧，一般都是单数，exception

2024-02-29 02:49 UTC, zhuyuqing commented on client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
> +        throw new IginxRuntimeException("Parse Parameter error.");
client的exception不能算是IGinXRuntime异常吧
只有IGinX引擎本身的才是IGinXRuntime部分

2024-02-29 02:49 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/migration/MigrationPolicy.java
> +              this.LOGGER.info("start migration: {}", migrationTask);
这个命名看着不太一致

2024-02-29 02:49 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/migration/MigrationPolicy.java
> +    } catch (PhysicalException e) {
所以，PhysicalException和PhysicalRuntimException是怎么区分的？

2024-02-29 02:49 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/insert/DataPointsParser.java
> +    // 构造查询
为啥这段后面不会抛exception了？

2024-02-29 02:49 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/insert/DataPointsParser.java
> +  private void sendMetricsData() {
为啥这个声明不需要了？

2024-03-06 08:26 UTC, aqni approved these changes

2024-03-06 08:41 UTC, RemHero commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/MemoryPhysicalTaskDispatcher.java
> +                                new PhysicalException("unexpected exception: " + e.getMessage()));
等同于Exception 和 RuntimeException的区别

2024-03-06 08:41 UTC, RemHero commented on shared/src/main/java/cn/edu/tsinghua/iginx/exceptions/IginxRuntimeException.java
> +/*
已改

2024-03-06 08:41 UTC, RemHero commented on client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
> +        throw new IginxRuntimeException("Parse Parameter error.");
已改

2024-03-06 08:44 UTC, RemHero commented on core/src/main/java/cn/edu/tsinghua/iginx/migration/MigrationPolicy.java
> +              this.LOGGER.info("start migration: {}", migrationTask);
已改

2024-03-06 08:44 UTC, RemHero commented on core/src/main/java/cn/edu/tsinghua/iginx/migration/MigrationPolicy.java
> +    } catch (PhysicalException e) {
已改

2024-03-06 08:46 UTC, RemHero commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/insert/DataPointsParser.java
> +    // 构造查询
这里不进行catch，在上层统一catch

2024-03-06 08:48 UTC, RemHero commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/insert/DataPointsParser.java
> +  private void sendMetricsData() {
优化了不会抛出Exception的代码

2024-03-08 09:19 UTC, zhuyuqing requested changes

2024-03-08 09:19 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorDev.java
> +      default:
所有类似 地需要处理一下

2024-03-08 09:19 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorDiff.java
> +        throw new IllegalArgumentException("Unsupported data type");
处理一下

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/FileSystemManager.java
>    public Exception trimFilesContent(
返回值改掉

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/LocalExecutor.java
> +              String.format("read file error, paths %s filter %s", paths, filter), e));
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/exec/LocalExecutor.java
> +    } catch (Exception e) {
改成具体的Exception

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new RuntimeException(
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new IOException(
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new IOException(
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new RuntimeException(
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new RuntimeException(
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new RuntimeException(String.format("trim file %s failure", file.getAbsolutePath()), e);
改

2024-03-08 09:19 UTC, zhuyuqing commented on dataSources/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBStorage.java
> +      throw new RuntimeException("get time series failure: ", e);
都 改了吧

2024-03-08 09:35 UTC, zhuyuqing requested changes

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/db/lsm/OneTierDB.java
> +      throw new RuntimeException(e);
这个应该是继承physicalException的异常吧？
全改了吧

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
> +      throw new StorageInitializationException("cannot connect to " + meta + " : " + e);
昨天说的是不能这么写的？改

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
>        throw new StorageInitializationException("unexpected database: " + meta.getStorageEngine());
改吧

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
> +              throw new PhysicalTaskExecuteFailureException(
改吧

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
> +      throw new PhysicalTaskExecuteFailureException("failed to get databases of " + meta, e);
都改了吧

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
> +      throw new PhysicalException("failed to close connection", e);
改吧，不合规范

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/query/entity/PostgreSQLQueryRowStream.java
> +      LOGGER.error("error occurred when closing resultSets or connections", e);
不合规范

2024-03-08 09:35 UTC, zhuyuqing commented on dataSources/redis/src/main/java/cn/edu/tsinghua/iginx/redis/RedisStorage.java
> +    List<String> queryPaths =
这里没有异常吗？

2024-03-08 09:35 UTC, zhuyuqing commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/IginxDataSource.java
> +      LOGGER.log(Level.SEVERE, e, () -> "Failed to get connection");
这个为啥和前面的不一样？

2024-03-08 09:35 UTC, zhuyuqing commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/IginxPreparedStatement.java
> +      LOGGER.log(Level.SEVERE, e, () -> "Error occurs when creating complete sql");
这个为啥和前面的不一样

2024-03-08 09:35 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ValueUtils.java
> +      throw new IllegalArgumentException("Unexpected data type: " + value.getClass());
这个不一样

2024-03-08 13:18 UTC, RemHero commented on dataSources/redis/src/main/java/cn/edu/tsinghua/iginx/redis/RedisStorage.java
> +    List<String> queryPaths =
Redis优化了异常抛出，删除了不必要异常

2024-03-10 14:10 UTC, RemHero commented on dataSources/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/file/DefaultFileOperator.java
> +      throw new IOException(
这里的异常包装了不同的信息，是允许这样做的。以下这种代码是不允许的，因为没有包装任何有用信息，知识单纯的嵌套
```java
catch (IOException e) {
      LOGGER.error("write iginx file {} failure: ", file.getAbsolutePath(), e);
      throw new IOException(e);
```

2024-03-23 02:57 UTC, closed without merging