union the test
IGinX-THU/IGinX pull request #25
Opened 2023-02-24 00:48 UTC by RemHero

2023-02-25 06:13 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/MultiConnection.java
> +package cn.edu.tsinghua.iginx.integration.tool;
这是一个没有变化的文件，为啥要删掉再加进来？

2023-02-25 06:14 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testTask.txt
> +IoTDBSQLSessionIT
这些测试的名字是不是要重构一下？比如，前面的IoTDBSQLSessionIT，现在应该是对所有数据库者可用的？

2023-02-25 06:15 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testConfig.properties
> +# the normal test TagIT,RestAnnotationIT,RestIT,TransformIT,SessionV2IT
为啥会有不同数据库的测试区分？

2023-02-25 13:04 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/MultiConnection.java
> +package cn.edu.tsinghua.iginx.integration.tool;
我对测试的文件结构test目录进行了调整，让测试结构更加的清晰

2023-02-25 13:05 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testTask.txt
> +IoTDBSQLSessionIT
这个文件的内容会被覆盖，这里只是展示，SQLSessionIT 已经可以对所有数据库进行测试

2023-02-25 13:11 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testConfig.properties
> +# the normal test TagIT,RestAnnotationIT,RestIT,TransformIT,SessionV2IT
目前的测试框架已经将之前所有的测试融入。之前有什么测试，现在就有什么测试。那些通用测试也已经对所有数据库实现了，没问题。其次，这样写也更加灵活，而且本身就需要对不同数据库进行测试，有区分很正常，符合测试逻辑。

2023-02-25 13:47 UTC, RemHero commented
# Union the Test
该 pr 的目的有两个
- [√]  **融合目前的测试，缩短测试时间**。目前从原来的近1h的测试，压缩到现在15min的测试。
- [√]  **优化测试结构**。对每个数据库进行测试。现有的测试结构继承了原来所有的测试，并支持便捷地添加针对每个数据库的测试；同时，调整了测试的结构，结构如下
```c
test
|- dbtest        针对各个数据库的测试
|- expansion     扩容测试
|- func          针对IGinX的功能测试
|- mds           针对元数据空间的测试
```

### 新增 IGinX 功能测试
1、在[`func`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/func)目录下实现测试方法
2、向[ `testConfig.properties`](https://github.com/RemHero/IGinX/blob/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testConfig.properties)配置文件中加对应测试方法

### 新增针对数据库测试
1、在[`dbtest`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/dbtest)目录下添加对应数据库测试方法
2、在`testConfig.properties` 中加对应数据库名称以及信息

### 新增 Expansion 测试
1、在[`expansion`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion)目录下添加对应数据库的两个方法类`HistoryDataGenerator`和`HistoryDataCapacityExpansionIT`

2023-02-26 02:33 UTC, zhuyuqing commented
> # Union the Test
> 该 pr 的目的有两个
> 
> * [√]  **融合目前的测试，缩短测试时间**。目前从原来的近1h的测试，压缩到现在15min的测试。
> * [√]  **优化测试结构**。对每个数据库进行测试。现有的测试结构继承了原来所有的测试，并支持便捷地添加针对每个数据库的测试；同时，调整了测试的结构，结构如下
> 
> ```c
> test
> |- dbtest        针对各个数据库的测试
> |- expansion     扩容测试
> |- func          针对IGinX的功能测试
> |- mds           针对元数据空间的测试
> ```
> 
> ### 新增 IGinX 功能测试
> 1、在[`func`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/func)目录下实现测试方法 2、向[ `testConfig.properties`](https://github.com/RemHero/IGinX/blob/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/testcontroler/testConfig.properties)配置文件中加对应测试方法
> 
> ### 新增针对数据库测试
> 1、在[`dbtest`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/dbtest)目录下添加对应数据库测试方法 2、在`testConfig.properties` 中加对应数据库名称以及信息
> 
> ### 新增 Expansion 测试
> 1、在[`expansion`](https://github.com/RemHero/IGinX/tree/IT/test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion)目录下添加对应数据库的两个方法类`HistoryDataGenerator`和`HistoryDataCapacityExpansionIT`

2023-02-27 08:54 UTC, zhuyuqing requested changes
Please update. Thanks!~

2023-02-27 08:54 UTC, zhuyuqing commented on .github/workflows/DB-CE.yml
> +            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#oriHasDataExpHasData -DfailIfNoTests=false
这个问题并未处理

2023-02-28 01:05 UTC, closed without merging