feat(parquet): implement file compression
IGinX-THU/IGinX pull request #254
Opened 2024-02-21 01:47 UTC by aqni

| 格式    | 解压 | 压缩 | 库             |
|---------|------|------|----------------|
| SNAPPY  | √    | √    | aircompressor  |
| GZIP    | √    | √    | jdk            |
| LZO     | √    | √    | aircompressor  |
| BROTLI  | √    | ×    | org.brotli.dec |
| LZ4     | √    | ×    | aircompressor  |
| ZSTD    | √    | √    | zstd-jni       |
| LZ4_RAW | √    | √    | aircompressor  |

2024-02-23 12:18 UTC, zhuyuqing requested changes

2024-02-23 12:18 UTC, zhuyuqing commented on dataSources/parquet/pom.xml
> +            <version>0.0.1</version>
相应仓库没有对应的版本？

2024-02-23 12:22 UTC, aqni commented on dataSources/parquet/pom.xml
> +            <version>0.0.1</version>
在page分支发布了

2024-02-23 12:26 UTC, aqni commented on dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/manager/dummy/Loader.java
> +      DataType iginxType = IParquetReader.toIginxType(primitiveType);
dummy和非dumm使用的相同的库，只要非dummy能解压，dummy就能。

2024-02-23 12:27 UTC, aqni commented on dataSources/parquet/src/test/java/cn/edu/tsinghua/iginx/parquet/io/ParquetFormatIOTest.java
> +            new String[] {"s1", "s2", "s3", "s4", "s5", "s6"},
改成默认带snappy压缩的了

2024-02-23 12:28 UTC, aqni commented on dataSources/parquet/src/test/java/cn/edu/tsinghua/iginx/parquet/io/ParquetFormatIOTest.java
> +            new String[] {"s1", "s2", "s3", "s4", "s5", "s6"},
dummy测试没改，还是不带压缩的。非dummy是带压缩的，单元测试一部分带压缩。

2024-02-29 03:00 UTC, zhuyuqing commented on conf/config.properties
> +#storageEngineList=127.0.0.1#6667#parquet#dir=/path/to/your/parquet#dummy_dir=/path/to/your/data#iginx_port=6888#has_data=false#is_read_only=false#thrift_timeout=30000#thrift_pool_max_size=100#thrift
既然已经过时，那就不考虑LZ4了吧

2024-02-29 03:01 UTC, zhuyuqing commented on dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/manager/dummy/Loader.java
> +      DataType iginxType = IParquetReader.toIginxType(primitiveType);
压缩的元信息在Parquet文件里存着吗？

2024-02-29 03:02 UTC, zhuyuqing commented on dataSources/parquet/src/test/java/cn/edu/tsinghua/iginx/parquet/io/ParquetFormatIOTest.java
> +            new String[] {"s1", "s2", "s3", "s4", "s5", "s6"},
在Parquet仓库中，ExampleParquetWriter/Reader里，好像没看到配置压缩这一项？

2024-02-29 03:03 UTC, zhuyuqing commented on conf/config.properties
> +#storageEngineList=127.0.0.1#6667#parquet#dir=/path/to/your/parquet#dummy_dir=/path/to/your/data#iginx_port=6888#has_data=false#is_read_only=false#thrift_timeout=30000#thrift_pool_max_size=100#thrift
还有BROTLI呢？

2024-02-29 03:47 UTC, aqni commented on dataSources/parquet/src/test/java/cn/edu/tsinghua/iginx/parquet/io/ParquetFormatIOTest.java
> +            new String[] {"s1", "s2", "s3", "s4", "s5", "s6"},
`ExampleParquetWriter.Builder`的继承自`ParquetWriter.Builder`。用`withCompressionCodec`来设置Writer的压缩编码。Reader是根据文件实际用的压缩算法来选择的，不需要选择。
在这里有例子：
[ExampleParquetWriterTest.java#L63](https://github.com/IGinX-THU/Parquet/blob/b0ce032c5306e11e0228b07d6e29c752bd42daa6/src/test/java/cn/edu/tsinghua/iginx/format/parquet/example/ExampleParquetWriterTest.java#L63)

2024-02-29 03:57 UTC, aqni commented on dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/manager/dummy/Loader.java
> +      DataType iginxType = IParquetReader.toIginxType(primitiveType);
Parquet文件里存着实际存储的数据是用哪种压缩算法压缩的。

2024-02-29 04:09 UTC, aqni commented on conf/config.properties
> +#storageEngineList=127.0.0.1#6667#parquet#dir=/path/to/your/parquet#dummy_dir=/path/to/your/data#iginx_port=6888#has_data=false#is_read_only=false#thrift_timeout=30000#thrift_pool_max_size=100#thrift
BROTL的编码库只有jni版本（Brotli4j）的，解码库有纯java版本的。
jni版本封装的可移植性并不好，在windows平台上要求安装 Microsoft Visual C++ Redistributable。
而且BROTL是十分慢的压缩算法，所以没有添加到Parquet的压缩实现中。

2024-03-05 04:33 UTC, aqni commented
请先合并https://github.com/IGinX-THU/IGinX/pull/262

2024-03-08 08:08 UTC, merged