Refactor log style
IGinX-THU/IGinX pull request #278
Opened 2024-03-18 09:16 UTC by aqni

2024-03-20 02:41 UTC, Yihao-Xu requested changes

2024-03-20 02:41 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/JobRunner.java
>            String.format("Fail to close Transform job runner id=%d, because", job.getJobId()), e);
这里没改成LOGGER的格式，还是String.format

2024-03-20 02:41 UTC, Yihao-Xu commented on core/src/test/java/cn/edu/tsinghua/iginx/metadata/entity/ColumnsIntervalTest.java
> +        LOGGER.error("expect true but was false, with {}", str);
这里怎么不打印error的信息？

2024-03-20 02:41 UTC, Yihao-Xu commented on core/src/test/java/cn/edu/tsinghua/iginx/transform/YamlReadTest.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(YAMLReader.class);
这里是不是该用YAMLReaderTest.class？看上去原来就没写对

2024-03-20 02:41 UTC, Yihao-Xu commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/IginXDataSource.java
> +  private static final Logger LOGGER = Logger.getLogger(IginXDataSource.class.getName());
为什么这里用的是Logger？上面用的都是LoggerFactory，有什么区别？

2024-03-20 02:41 UTC, Yihao-Xu commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/Utils.java
> +  private static final Logger LOGGER = Logger.getLogger(Utils.class.getName());
同上

2024-03-20 02:41 UTC, Yihao-Xu commented on jdbc/src/test/java/ExampleTest.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(ExampleTest.class.getName());
同上

2024-03-20 02:41 UTC, Yihao-Xu commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/YAMLReader.java
> +        LOGGER.error("Fail to close the file, path=%s", filePath);
这里感觉不太对，像是之前就忘记加String.format一样，把 %s去掉？

2024-03-21 04:03 UTC, aqni commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/IginXDataSource.java
> +  private static final Logger LOGGER = Logger.getLogger(IginXDataSource.class.getName());
jdbc里要求使用jdk自带的日志接口，所以是这种格式，我们其他地方使用的是slf4j。

2024-03-21 04:18 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/YAMLReader.java
> +        LOGGER.error("Fail to close the file, path=%s", filePath);
已改正

2024-03-21 04:18 UTC, aqni commented on jdbc/src/test/java/ExampleTest.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(ExampleTest.class.getName());
已改正

2024-03-21 04:18 UTC, aqni commented on jdbc/src/main/java/cn/edu/tsinghua/iginx/jdbc/Utils.java
> +  private static final Logger LOGGER = Logger.getLogger(Utils.class.getName());
同上

2024-03-21 04:18 UTC, aqni commented on core/src/test/java/cn/edu/tsinghua/iginx/metadata/entity/ColumnsIntervalTest.java
> +        LOGGER.error("expect true but was false, with {}", str);
已改正

2024-03-21 04:19 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/JobRunner.java
>            String.format("Fail to close Transform job runner id=%d, because", job.getJobId()), e);
已改正该问题及类似问题

2024-03-21 04:27 UTC, aqni commented on core/src/test/java/cn/edu/tsinghua/iginx/transform/YamlReadTest.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(YAMLReader.class);
已改正

2024-03-29 09:09 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/policy/simple/FragmentCreator.java
> +              LOGGER.error("unexpected error: ", e);
重复报错

2024-03-29 09:11 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/rest/bean/Annotation.java
> +      LOGGER.error("unexpected error: ", e);
合并

2024-03-29 09:44 UTC, SolomonAnn approved these changes

2024-04-11 01:56 UTC, merged