fix(shared,deps): remove jcenter repo & fix injection and Inefficiency of regular expression
IGinX-THU/IGinX pull request #279
Opened 2024-03-19 02:50 UTC by aqni

解决了CodeQL提示的其中3个问题。剩余工作是检查文件路径工作，其修改量较大，需要进一步讨论并另提PR

2024-03-23 01:10 UTC, zhuyuqing requested changes

2024-03-23 01:10 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +    if (!name.contains("*")) return Pattern.quote(name);
这个语义改变了吧

2024-03-23 01:10 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +    return paths.stream().anyMatch(s -> !s.isEmpty() && s.chars().allMatch(c -> c == '*'));
这两个的语义看起来也不是一样的吧

2024-03-25 04:35 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +    return paths.stream().anyMatch(s -> !s.isEmpty() && s.chars().allMatch(c -> c == '*'));
已删除

2024-03-25 04:45 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +    if (!name.contains("*")) return Pattern.quote(name);
根据 git history 说一下这个函数的修改始末

### 最初一版

```java
public static String reformatColumnName(String name) {
    if (!name.contains("*") && !name.contains("(") && !name.contains(")"))
        return name;
    name = name.replaceAll("[.]", "[.]");
    name = name.replaceAll("[*]", ".*");
    name = name.replaceAll("[(]", "[(]");
    name = name.replaceAll("[)]", "[)]");
    return name;
}
```

这个函数用来将通配符转换成正则表达式，由于`()`是特殊字符，所以需要进行替换。`!name.contains("*") && !name.contains("(") && !name.contains(")")` 判断的目的如果不存在这些特殊字符，则跳过后面的替换，来提高性能。是否保留这个条件判断不影响正确性。

### 第二个版本

```java
  private static String reformatColumnName(String name) {
    if (!name.contains("*") && !name.contains("(") && !name.contains(")")) return name;
    name = name.replaceAll("[.]", "[.]");
    name = name.replaceAll("[*]", ".*");
    name = name.replaceAll("[(]", "[(]");
    name = name.replaceAll("[)]", "[)]");
    name = name.replaceAll("[{]", "[{]");
    name = name.replaceAll("[}]", "[}]");
    name = name.replaceAll("[+]", "[\\\\+]");
    name = name.replaceAll("\\$", "[\\$]");
    name = name.replaceAll("\\^", "[\\\\^]");
    name = name.replaceAll("\\\\", "\\\\\\\\");
    return name;
  }
```

由于后面某个时间IGinX支持了更多的特殊字符，所以需要替换更多的字符，但是没有修改这个条件判断。

由于支持了更多特殊字符，不修改这个条件判断会影响正确性，例如`a+`这个路径，它只需要匹配`a+`这个字符串本身，但是在上面的逻辑中，由于直接跳过了后面的特殊字符替换，当作正则表达式进行匹配时，它也会匹配`aa`,`aaa`等字符串。

### 本次修改

条件判断改成`if (!name.contains("*")) return Pattern.quote(name);`的意思是没有通配符就直接用字符串字面值进行正则匹配，就可以省掉后面的字符串替换。

除了上面的正确性问题外，修改这一处还有另外的原因“

2024-03-29 07:44 UTC, SolomonAnn approved these changes

2024-03-30 02:28 UTC, merged