fix(core): response success and spin for IStorage when init of storag…
IGinX-THU/IGinX pull request #282
Opened 2024-03-21 09:50 UTC by aqni

### BUG 复现及效果

1. 以 parquet 作为初始存储引擎启动IGinX
2. 删除 postgresql 的 driver 文件，即删除 `driver/postgresql` 文件夹
3. 在命令行客户端执行 ` add storageengine("101.6.15.203",65432,"postgresql","username:postgre,password:123456,has_data:true");`
4. 客户端返回执行成功 
5. IGinX 无限循环打印错误日志 `spinning for IStorage！`

### 修复方式

返回成功的原因，

2024-03-23 02:56 UTC, zhuyuqing requested changes

2024-03-23 02:56 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> -    if (!metaManager.addStorageEngines(otherMetas)) {
这一批语句，在先后顺序上，是要考究的，这样修改的话，需要进一步确认，顺序不影响，并发测试没问题

2024-03-25 05:48 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> -    if (!metaManager.addStorageEngines(otherMetas)) {
### 先后顺序没有改变

旧的实现

```java
if (!metaManager.addStorageEngines(otherMetas)) { // 先添加所有元数据（在内部实现中是逐个元数据进行添加，而不是一次性添加所有的存储引擎元数据）
  logger.error("add storage engines failed.");
  status.addToSubStatus(RpcUtils.FAILURE);
}
for (StorageEngineMeta meta : otherMetas) { 
  storageManager.addStorage(meta); // 逐个添加存储引擎（内部实现分两步：1.初始化存储引擎对象 2.将该对象添加到storageManager中）
}
```

新的实现

```java
for (StorageEngineMeta meta : otherMetas) { // 逐个添加元数据并添加存储引擎
  IStorage storage = storageManager.initRemoteStorage(meta); // 初始化对象
  if (storage == null) {
    status.addToSubStatus(
        RpcUtils.status(StatusCode.STATEMENT_EXECUTION_ERROR, "init storage engine failed"));
    continue;
  }
  if (!metaManager.addStorageEngines(Collections.singletonList(meta))) { // 添加元数据
    logger.error("add storage engine {} failed.", meta);
    status.addToSubStatus(RpcUtils.FAILURE);
    continue;
  }
  storageManager.addStorage(meta, storage); // 添加前面初始化的对象到 storageManager
}
```

对于每一个需要添加的`StorageEngineMeta`，其先后顺序保持不变。

### 佐证

原 467-474 行是针对 filesystem 和 parquet 两个嵌入式存储引擎进行特殊处理的逻辑。也按照先初始化对象、再添加元数据、最后添加到StorageManager的顺序进行执行。

2024-03-29 03:46 UTC, zhuyuqing requested changes

2024-03-29 03:46 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +      IStorage storage = storageManager.initRemoteStorage(meta);
这些不是先初始化了一个远程存储吗？
还有个问题，为啥embedded不需要？

2024-03-29 04:06 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +      IStorage storage = storageManager.initRemoteStorage(meta);
一个这个操作
```java
storageManager.addStorage(meta);
```
等价于连续的两个操作
```java
IStorage storage = storageManager.initRemoteStorage(meta);
storageManager.addStorage(meta, storage); 
```

我的修改直接将原来的一个操作，等价地拆分为上述两个操作，当初始化远程存储失败时，不添加到元数据。修改前的逻辑是，无论远程存储是否初始化成功，该存储引擎总是被添加到元数据。

embedded也是先初始化了一个本地的存储引擎，再添加元数据。

2024-03-29 08:55 UTC, SolomonAnn approved these changes

2024-03-30 03:20 UTC, merged