Refactor(IGinX): merge duplicated code(part 1)
IGinX-THU/IGinX pull request #284
Opened 2024-03-22 03:16 UTC by shinyano

# Changes:
extract duplicated code/methods into abstract class or turn into object methods

# Finished module:
- core
  - auth
  - compaction
  - conf
  - metadata
  - policy

2024-03-29 03:36 UTC, zhuyuqing approved these changes
LGTM

2024-03-29 03:46 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/etcd/ETCDMetaStorage.java
>    private static final String STORAGE_UNIT_ID = "/id/storage_unit/";
其他地方都改成了unit，这里保留storage_unit不确定是否有问题

2024-03-29 03:57 UTC, SolomonAnn commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/etcd/ETCDMetaStorage.java
> -  private static final String STORAGE_LOCK = "/lock/storage/";
注意到这些字符串的末尾有的有“/”，有的没有，修改后全部去掉了“/”，不确定是否有影响

2024-03-29 04:03 UTC, SolomonAnn commented
建议在本地使用etcd跑一下测试

2024-03-29 14:35 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/etcd/ETCDMetaStorage.java
>    private static final String STORAGE_UNIT_ID = "/id/storage_unit/";
测试没有问题，不过还是改成unit和zk保持一致了

2024-04-12 04:13 UTC, zhuyuqing requested changes

2024-04-12 04:13 UTC, zhuyuqing commented on .github/workflows/standalone-test-pushdown.yml
> +                metadata: [zookeeper, etcd]
这次合并，我们先把这行变成只有ZK

2024-04-12 04:13 UTC, zhuyuqing commented on .github/workflows/standalone-test.yml
> +                metadata: [zookeeper, etcd]
这次合并，我们先把这行变成只有ZK

2024-04-12 04:13 UTC, zhuyuqing commented on .github/workflows/case-regression.yml
> +                metadata: [zookeeper, etcd]
这次合并，我们先把这行变成只有ZK

2024-04-12 04:13 UTC, zhuyuqing commented on .github/workflows/DB-CE.yml
> +                metadata: [zookeeper, etcd]
这次合并，我们先把这行变成只有ZK

2024-04-13 05:02 UTC, merged