feat(core): manage file access permissions by config
IGinX-THU/IGinX pull request #289
Opened 2024-04-04 11:18 UTC by aqni

详见文档：https://oxlh5mrwi0.feishu.cn/docx/IR6hdgBgAo6HUNxQyRZchw39nOf

2024-04-06 03:54 UTC, zhuyuqing requested changes

2024-04-06 03:54 UTC, zhuyuqing commented on core/src/main/resources/file-permission.properties
> +default.default[0].read=false
用户只写了defaut.default[1]，能处理对吗？
这个下标完全可以通过用户自定义的命名实现，系统还是应当简化

2024-04-06 04:02 UTC, zhuyuqing requested changes

2024-04-06 04:02 UTC, zhuyuqing commented on core/src/main/resources/file-permission.properties
> +root.default[0].include=glob:**
为啥是**，而不是*？

2024-04-06 04:02 UTC, zhuyuqing commented on core/src/main/resources/file-permission.properties
> +root.default[0].include=glob:**
一般正则都是*，这是应当按照用户习惯来

2024-04-06 04:04 UTC, zhuyuqing requested changes

2024-04-06 04:04 UTC, zhuyuqing commented on core/src/main/resources/file-permission.properties
> +#
这个文件按理说，在编译后，应当拷贝到conf目录下一份，里面的说明让用户可以知道，否则用户无从了解如何设置文件配置

2024-04-06 04:08 UTC, zhuyuqing commented on core/src/main/resources/file-permission.properties
> +default.transformer[0].execute=true
什么情况可以做到能执行，但不能读？这一般是允许的吗？

2024-04-07 00:24 UTC, aqni commented on core/src/main/resources/file-permission.properties
> +root.default[0].include=glob:**
*是匹配不跨目录的路径，**是匹配跨目录的路径，这个语法和命令行中通配符语法是一样的

2024-04-07 00:30 UTC, aqni commented on core/src/main/resources/file-permission.properties
> +#
拷贝了，可以在在mavem assembly插件配置的修改中看到

2024-04-07 00:50 UTC, aqni commented on core/src/main/resources/file-permission.properties
> +default.transformer[0].execute=true
比如udf我们只希望用户执行它，但是不能获得具体的python代码。

2024-04-07 02:33 UTC, aqni commented on core/src/main/resources/file-permission.properties
> +default.default[0].read=false
### 优先级覆盖了所有情况

1. 首先匹配特定用户的配置，接着匹配 default 用户配置。
2. 首先匹配特定模块的配置，接着匹配 default 模块的配置。
3. 首先匹配高优先级的规则，接着匹配低优先级的规则，应用第一个匹配的规则。
4. 没有规则被匹配则不对权限进行限制（也就是 rwx都是true）。

### 优先级冲突

如果是同一个用户的同一个模块优先级数字重复了，例如`default.default[0]`出现两次，会保留第一次

这些都在file-permission.properties中已经说明了

2024-04-07 02:54 UTC, aqni commented on core/src/main/resources/file-permission.properties
> +default.default[0].read=false
> 如果只按之前讲的，从前到后的apply，如何不能实现类似需求？

之前讨论过，需要在键中加一个`[0] [1] ...` 来避免键值对的键重复，既然已经加了 0 1 2，不妨按照 0 1 2 来指定优先级

2024-04-07 10:45 UTC, SolomonAnn approved these changes

2024-04-08 01:38 UTC, merged