docs(exception): add exception README
IGinX-THU/IGinX pull request #291
Opened 2024-04-08 02:25 UTC by RemHero

2024-04-08 07:38 UTC, aqni commented
我个人觉得，既然这个文档只是写给开发者看的，而不是写给用户看的。那应该直接写在 javadoc 注释中，具体应该写在 `core/src/main/java/cn/edu/tsinghua/iginx/exception/package-info.java`中

2024-04-09 08:05 UTC, aqni approved these changes

2024-04-10 08:59 UTC, zhuyuqing requested changes

2024-04-10 08:59 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/exception/package-info.java
> + * <h2>dataSources模块 </h2>
既然采用了这个规范，能否一次到位？
使用<h1><h3>这样的标签应该不能为javadoc所识别处理吧？

2024-04-12 02:46 UTC, zhuyuqing requested changes

2024-04-12 02:46 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/exception/IginxException.java
>    private static final long serialVersionUID = -1355829042896588219L;
这个ID是用于做什么区分的？为啥是这个数？是否有更确定的机制生成它？

2024-04-12 03:16 UTC, merged