add pysession tests
IGinX-THU/IGinX pull request #300
Opened 2024-04-11 09:08 UTC by Janet731

2024-04-11 09:31 UTC, shinyano commented on session_py/tests/tests.py
> +            session.open()
放到init里面

2024-04-11 09:33 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +    System.out.println(os);
把这些输出都删掉，或者放到logger里面

2024-04-11 09:33 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +      pythonCMD = "python3";
这个在action脚本里改过

2024-04-11 09:36 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +      interpreter.exec("t = tests.Tests()");
初始化的过程放到构造函数内

2024-04-12 02:32 UTC, Yihao-Xu requested changes

2024-04-12 02:32 UTC, Yihao-Xu commented on session_py/tests/tests.py
这个文件，以及a、b、a.csv都是PySessionIT测试用的吧，那是不是应该放到test模块的resource里去？
![image](https://github.com/IGinX-THU/IGinX/assets/48053143/093ce370-57b5-4b49-875d-3f1b9468db28)

2024-04-18 03:29 UTC, Yihao-Xu requested changes

2024-04-18 03:29 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +            "Time\tpath\tvalue\t",
这些测试结果，包括其他的可读性太差了，为什么不考虑全部转换成dataframe再对比测试？

2024-04-18 03:29 UTC, Yihao-Xu commented on session_py/tests/tests.py
tests.py也是测试用的，不放到测试resource里是为什么？

2024-04-22 02:22 UTC, Yihao-Xu approved these changes

2024-04-26 04:20 UTC, merged