refactor(sql): adjust UDF sql
IGinX-THU/IGinX pull request #306
Opened 2024-04-15 02:29 UTC by shinyano

# New sql:
- drop UDF:
```
DROP FUNCTION <udfName>;
```
old: `DROP PYTHON TASK <udfName>;`
- list all UDFs:
```
SHOW FUNCTIONS;
```
old: `SHOW REGISTER PYTHON TASK;`

2024-04-15 09:33 UTC, SolomonAnn commented on example/src/main/java/cn/edu/tsinghua/iginx/session/TransformCompare.java
> +  private static final String SHOW_REGISTER_TASK_SQL = "SHOW FUNCTIONS;";
变量名做相应修改

2024-04-15 09:35 UTC, SolomonAnn commented on example/src/main/java/cn/edu/tsinghua/iginx/session/TransformExample.java
> +  private static final String SHOW_REGISTER_TASK_SQL = "SHOW FUNCTIONS;";
变量名做相应修改

2024-04-15 09:36 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/TransformIT.java
> +  private static final String SHOW_REGISTER_TASK_SQL = "SHOW FUNCTIONS;";
变量名做相应修改

2024-04-15 14:09 UTC, shinyano commented on example/src/main/java/cn/edu/tsinghua/iginx/session/TransformCompare.java
> +  private static final String SHOW_REGISTER_TASK_SQL = "SHOW FUNCTIONS;";
已修改

2024-04-20 02:47 UTC, zhuyuqing requested changes

2024-04-20 02:47 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> -   | DROP PYTHON TASK name = stringLiteral # dropTaskStatement
python task等关键字没用了吧？去掉吧

2024-04-20 02:47 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> -   | DROP PYTHON TASK name = stringLiteral # dropTaskStatement
还有register?

2024-04-21 16:23 UTC, shinyano commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> -   | DROP PYTHON TASK name = stringLiteral # dropTaskStatement
已删除

2024-04-22 02:03 UTC, zhuyuqing approved these changes

2024-04-22 02:04 UTC, merged