feat(udf): allow remote UDF registeration
IGinX-THU/IGinX pull request #308
Opened 2024-04-16 03:44 UTC by shinyano

# New feature:
User can register UDFs using local python scripts into iginx that runs on a different host.

# Usage:
- client
Use normal sql. Session will decide whether the iginx is on a different host based on connection parameters.
- session
Use `executeRegisterTask(sql)` method.
**NOTES** Currently session provides `executeRegisterTask(sql, isRemote)` to perform loading remote scripts, ignoring whether iginx is really on a different host. This is for testing only, and can be optimized if we find a better way to do tests.

2024-04-20 03:28 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +  private void executeReg(String statement, boolean isRemote) {
在单机测试下，该函数isRemote传入true是否有意义？

2024-04-20 03:29 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +  public void testRemoteFileReg() {}
补充关于remote的测试，需保证client和server在不同节点上

2024-05-03 10:14 UTC, zhuyuqing requested changes
remote tests can be and should be added.

2024-05-15 07:15 UTC, SolomonAnn commented on client/src/assembly/resources/sbin/start_cli.sh
> +echo ${PARAMETERS[@]}
这是为了调试打印的日志吧

2024-05-15 07:37 UTC, SolomonAnn commented on .github/scripts/test/cli/test_remote_udf.sh
> +if [[ $os =~ "mac" ]]; then
这个脚本就是linux专用的吧，这里是不是应该删除

2024-05-15 07:39 UTC, SolomonAnn commented on .github/workflows/remote-test.yml
> +                    "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh" ${{ matrix.os }}
无需传入os

2024-05-15 10:44 UTC, merged