refactor(test): enhance test workflow
IGinX-THU/IGinX pull request #310
Opened 2024-04-16 14:13 UTC by RemHero

2024-04-18 03:21 UTC, SolomonAnn approved these changes

2024-04-19 07:42 UTC, Yihao-Xu approved these changes

2024-04-19 10:02 UTC, shinyano commented
LGTM

2024-04-20 02:35 UTC, zhuyuqing requested changes

2024-04-20 02:35 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/ConfLoader.java
> +      Properties properties = null;
这个类在loadTestConf的时候已经将配置load过一次了？

2024-04-22 07:34 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/ConfLoader.java
> +      Properties properties = null;
优化了，如果已经loadConf，那么直接读取

2024-04-25 02:59 UTC, zhuyuqing requested changes

2024-04-25 02:59 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/ConfLoader.java
> +        LOGGER.error("properties is not loaded, please load the conf first.");
这个改得也太草率了吧。。。
你的loadTestConf是在testUnion时候才被调用，所以，也就是说，所有调用getStorageType、isScaling或getDBCETestWay的函数，都必须等testUnion，也就是Union测试完成，才能调用成功？
但是，并不见得测试一定会先启动testUnion吧？
既然这个不是随测试引擎变化的conf，而且都要用到，为啥不到类初始化的时候直接就载入呢？。。。。。。。。

2024-04-25 03:32 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/ConfLoader.java
> +        LOGGER.error("properties is not loaded, please load the conf first.");
loadTestConf不是只在TestUnion时才调用，每个测试函数在启动时都会加载conf，所以在本地跑测试的时候就可以直接运行

2024-05-07 01:58 UTC, zhuyuqing approved these changes

2024-05-07 01:59 UTC, merged