fix(query): adjust query result in downsample function
IGinX-THU/IGinX pull request #347
Opened 2024-05-26 10:07 UTC by shinyano

# what's wrong
The key column in previous downsample query result is confusing. It refers to the start of a window in such results, while user would assume it is a key for a record.

# fix
Replace `key` with two columns: `window_start` and `window_end` to avoid misunderstanding.

doc:https://oxlh5mrwi0.feishu.cn/wiki/BUerw0yvQiGBgOkz6YjcfbXInvd

2024-05-29 08:52 UTC, SolomonAnn commented on thrift/src/main/proto/rpc.thrift
> +    10: required bool setInterval
变量最好不要以set开头，因为setter方法会变成setSetXXX

2024-05-30 10:01 UTC, SolomonAnn approved these changes

2024-06-03 07:35 UTC, zhuyuqing requested changes
需要去掉window_start, window_end两列

2024-06-03 07:52 UTC, shinyano commented
> 需要去掉window_start, window_end两列

flink 滑动窗口文档
https://nightlies.apache.org/flink/flink-docs-master/zh/docs/dev/table/sql/queries/window-tvf/#%e6%bb%91%e5%8a%a8%e7%aa%97%e5%8f%a3hop

2024-06-04 00:59 UTC, zhuyuqing commented
那调整一下语法，调整后的语法在会上过一下

2024-06-07 13:18 UTC, merged