feat(Optimizer): In Filter Transform Rule
IGinX-THU/IGinX pull request #359
Opened 2024-06-16 09:41 UTC by Yihao-Xu

2024-10-14 02:06 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      path = ctx.functionName().getText() + "(" + path + ")";
或许需要将functionName()转为为小写，类似 parseValueFilter 中的处理

2024-10-14 08:13 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      path = ctx.functionName().getText() + "(" + path + ")";
已修改

2024-10-14 08:15 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +      insert.append(String.format("(%d, %d, %d)", i, i % 100, i % 1000));
这个|in和&in测试的数据还是不同的，但是之前|not in和&not in的数据一样，主要是因为在us.d1.s1<100时看不出区别，现在新加了个where条件，测试100之后的数据，可以看出明显区别

2024-10-14 09:27 UTC, aqni approved these changes

2024-10-15 12:57 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/Op.java
> +
这两个函数现在没有用到了

2024-10-15 13:07 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/InFilter.java
> +    this.inOp = inOp.getOppositeOp();
这里需不需要考虑path带*的情况，比如对 us.*.d1 not in (1, 2) 取反之后的filter应该是 us.*.d1 &in (1, 2)，参考ValueFilter的实现。

2024-10-15 15:44 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/Op.java
> +
已修改

2024-10-16 01:40 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/Op.java
> +
isNotEqual在私有规则中有用到

2024-10-16 03:39 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +   | '!' IN
符号和IN之间能否有空格？

另外，这系列关键字组合是什么语义？
相应更新一下用户手册？

2024-10-18 02:01 UTC, jzl18thu approved these changes

2024-10-18 11:23 UTC, zhuyuqing requested changes

2024-10-18 11:23 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +    statement = "SELECT s1 FROM us.* WHERE s1 |NOT IN (1,2,3,6,8) AND s1 > 100 LIMIT 10;";
对于新增的 |IN和&IN ，类似之前的IN subquery测试用例，相应地增加两、三个测试吧

2024-10-18 11:26 UTC, zhuyuqing requested changes

2024-10-18 11:26 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +OPERATOR_NOT_IN_AND
之前有 !IN，所以才有这个和下面的？
现在是不是应该可以没有这两个了？否则，OR & NOT IN 这样吗？符合标准SQL规则吗？

2024-10-18 11:26 UTC, zhuyuqing commented on antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
> +OPERATOR_NOT_IN_AND
感觉有点奇怪，咱可以不用那么灵活

2024-10-24 01:08 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/InFilter.java
> +        case "!in":
这里感叹号可以去掉，下同

2024-10-28 02:53 UTC, merged