Feat(core): allow changing db params(only apply for dummy & read-only)
IGinX-THU/IGinX pull request #398
Opened 2024-07-19 08:13 UTC by shinyano

# New Feature
User can alter the params of read-only dummy storage engine. The HAS_DATA & IS_READ_ONLY attributes cannot be modified.

## SQL
```sql
ALTER STORAGEENGINE <engine_id> WITH PARAMS "(<param_key>:<param_value>,?)+";
```

## example:
``` sql
alter storageengine 2 with params "dummy_dir:test/new_data";
```

2024-07-20 04:15 UTC, zhuyuqing requested changes

2024-07-20 04:15 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/StorageEngineMeta.java
> +  private String ip;
对于5元组，它是唯一确定IGinX存储引擎的KEY，设置 为Final更合理，不应当改

2024-07-20 04:15 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/DefaultMetaManager.java
> +      boolean hasData = Boolean.parseBoolean(extraParams.getOrDefault(Constants.HAS_DATA, "true"));
默认不应当修改，修改后，不合IGinX逻辑

2024-07-20 04:15 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/utils/StorageEngineUtils.java
> +      boolean hasData = Boolean.parseBoolean(extraParams.getOrDefault(Constants.HAS_DATA, "true"));
同前

2024-07-20 04:15 UTC, zhuyuqing commented on test/src/test/resources/testConfig.properties
> +InfluxDB_mock=127.0.0.1#8086#InfluxDB#url=http://localhost:8086/#token=testToken#organization=testOrg#has_data=false#is_read_only=false
保持之前的默认，不应当修改此处

2024-07-20 04:15 UTC, zhuyuqing commented on .github/actions/dbRunner/action.yml
> +              statements: s|^#storageEngineList=127.0.0.1#3306#relational#engine=mysql#username=root#password=mysql#meta_properties_path=your-meta-properties-path|storageEngineList=127.0.0.1#3306#rel
虽然has_data默认不应当修改，但是你默认has_data改成了true，这里将has_data=false去掉，测试就会出错吧。

2024-07-22 09:36 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/StorageEngineMeta.java
> +  private String ip;
已修改

2024-07-22 09:36 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/DefaultMetaManager.java
> +      boolean hasData = Boolean.parseBoolean(extraParams.getOrDefault(Constants.HAS_DATA, "true"));
已修改

2024-07-22 09:36 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/utils/StorageEngineUtils.java
> +      boolean hasData = Boolean.parseBoolean(extraParams.getOrDefault(Constants.HAS_DATA, "true"));
已修改

2024-07-26 03:46 UTC, SolomonAnn approved these changes

2024-08-06 03:42 UTC, merged