feat(filestore): support reading nested directory and various file
IGinX-THU/IGinX pull request #423
Opened 2024-08-14 10:11 UTC by aqni

目前可以读取 parquet，其余文件按照以原始字节读取，兼容原 Filesystem 的用法。
但是，默认还是使用旧的 Filesystem 中的 Dummy 实现。
如果需要使用新的实现，需要配置对接层参数`dummy.struct=FileTree`。
通过`dummy.config.formats.RawChunk.pageSize`配置读取的块大小。

2024-08-15 01:41 UTC, aqni commented
请先合并 https://github.com/IGinX-THU/IGinX/pull/413

2024-08-16 03:25 UTC, jzl18thu requested changes

2024-08-16 03:25 UTC, jzl18thu commented on dataSource/filestore/src/main/java/cn/edu/tsinghua/iginx/filestore/struct/tree/query/ftj/TreeJoinQuerierBuilder.java
> +    try (DirectoryStream<Path> children = Files.newDirectoryStream(path)) {
要查询的pattern没有通配符时，可以把path继续下推

2024-08-16 07:27 UTC, aqni commented on dataSource/filestore/src/main/java/cn/edu/tsinghua/iginx/filestore/struct/tree/query/ftj/TreeJoinQuerierBuilder.java
> +    try (DirectoryStream<Path> children = Files.newDirectoryStream(path)) {
已修改，当路径中没有通配符时，避免遍历文件夹

2024-08-16 08:27 UTC, jzl18thu approved these changes

2024-09-03 08:17 UTC, merged