refactor(dataSource): remove parquet and filesystem project
IGinX-THU/IGinX pull request #424
Opened 2024-08-15 09:00 UTC by aqni

2024-08-15 09:01 UTC, aqni commented
需要先合并 https://github.com/IGinX-THU/IGinX/pull/423

2024-08-28 03:05 UTC, shinyano commented on assembly/pom.xml
> +                                    <value>storageEngineList=127.0.0.1#6667#filestore#dir=parquetData#iginx_port=6888</value>
这边的dir名字可以换一下

2024-08-28 03:49 UTC, aqni commented on assembly/pom.xml
> +                                    <value>storageEngineList=127.0.0.1#6667#filestore#dir=parquetData#iginx_port=6888</value>
名字改成了 data

2024-09-03 08:32 UTC, zhuyuqing requested changes

2024-09-03 08:32 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
> +                                        + " will not broadcasting to replicas for the sake of exception",
为啥要去掉人家的冒号？

2024-09-03 08:32 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/exception/package-info.java
> - * <p><b>Filesystem模块</b>
为啥没有新增FileStore模块？

2024-09-03 08:32 UTC, zhuyuqing commented on test/pom.xml
> -        <dependency>
这些依赖去掉没有问题吗？

2024-09-03 08:32 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> -  private static final String ADD_STORAGE_ENGINE_PARQUET =
有相应新增FileStore模块吗？

2024-09-03 08:32 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> -    // 处理parquet扩容操作
FileStore也需要有相应的测试吧

2024-09-03 08:32 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> -  private void testQueryForFileSystem() {
FileStore有这个测试吗？

2024-09-03 08:36 UTC, zhuyuqing requested changes

2024-09-03 08:44 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/exception/package-info.java
> - * <p><b>Filesystem模块</b>
这里除了 Filesystem 和 PostgreSQL 外都没有说明。似乎只是作为例子来说明，上面 PostgreSQL 仍然保留，可以作为例子。

2024-09-03 08:44 UTC, aqni commented on test/pom.xml
> -        <dependency>
这些依赖已经被各个对接层和core 依赖了，上面已经依赖了各个对接层和core，所以不需要手动再次指定。

2024-09-03 08:44 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
> -  private void testQueryForFileSystem() {
有这个测试，移动到专门测试 dummy 的函数中了。

2024-09-03 08:44 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> -  private static final String ADD_STORAGE_ENGINE_PARQUET =
FileStore 在原来的 filesystem 的基础上改的，有对应的测试。这些分支判断是专门处理 Parquet 旧 dummy 功能的，这部分功能已经移除了。

2024-09-03 08:44 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
> +                                        + " will not broadcasting to replicas for the sake of exception",
原来是用字符串拼接的方式获得字符串，所以需要用冒号分隔。现在是直接将异常交由日志 logger 来打印，所以不需要显示地再用冒号分隔。

2024-09-03 08:44 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/controller/Controller.java
> -    // 处理parquet扩容操作
同上
> FileStore 在原来的 filesystem 的基础上改的，有对应的测试。这些分支判断是专门处理 Parquet 旧 dummy 功能的，这部分功能已经移除了。

2024-09-03 08:47 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT _:@#$~^{} FROM _:@#$~^{};";
这个参数是专门测试原 FileSystem 对接层的非 Dummy 功能的，这部分功能已经移除了

2024-09-03 08:47 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT `1919810`._@#$.后缀 FROM 测试.前缀.`114514`;";
这个参数是专门测试原 FileSystem 对接层的非 Dummy 功能的，这部分功能已经移除了

2024-09-03 08:53 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +    assertFalse(result.get(1).contains("ip='127.0.0.1', port=6671, type='filestore'"));
这个测试是为了测试从 pysession 中添加 readonly 对接层实例的，重复应该没有问题，主要是我不知道应该如果重写这个测试，只能保留下来。

2024-09-03 08:54 UTC, aqni commented on test/src/test/resources/pySessionIT/tests.py
> -                    "thrift_timeout": "30000",
这些参数名称变了，在 conf.properites 中有

2024-09-03 08:54 UTC, aqni commented on test/src/test/resources/pySessionIT/tests.py
> -                    "thrift_pool_max_size": "100",
这些参数名称变了，在 conf.properites 中有

2024-09-03 09:05 UTC, aqni commented on test/src/test/resources/testConfig.properties
> +FileStore_port=6667,6668,6669
改成统一了，取代 parquet 的位置

2024-09-04 02:03 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT _:@#$~^{} FROM _:@#$~^{};";
Dummy+非Dummy的相关测试，应当尽量保留

2024-09-04 02:03 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +    assertFalse(result.get(1).contains("ip='127.0.0.1', port=6671, type='filestore'"));
请记录为TODO

2024-09-04 02:03 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT `1919810`._@#$.后缀 FROM 测试.前缀.`114514`;";
Dummy+非Dummy的相关测试，应当尽量保留

2024-09-05 07:30 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT _:@#$~^{} FROM _:@#$~^{};";
已经重写Dummy+非Dummy的相关测试

2024-09-05 07:31 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT `1919810`._@#$.后缀 FROM 测试.前缀.`114514`;";
Dummy+非Dummy的相关测试

2024-09-05 07:31 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/exception/package-info.java
> - * <p><b>Filesystem模块</b>
已经添加说明

2024-09-06 11:28 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/datasource/DataSourceIT.java
> -/*
为啥FileStore不需要这个测试？

2024-09-06 11:28 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT _:@#$~^{} FROM _:@#$~^{};";
这些测试在哪里？

2024-09-09 01:54 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/filesystem/datasource/DataSourceIT.java
> -/*
DataSourceIT 的正确位置应该是 `cn/edu/tsinghua/iginx/integration/datasource` 之前不知道为啥昊哲将其移动到了 filesystem 的测试文件夹下（我猜测是不小心），这次删除的时候我直接将整个 filesystem 测试文件夹删除，导致 DataSourceIT 代码丢失，现在已经将 DataSourceIT 恢复到正确位置。

2024-09-09 01:57 UTC, aqni commented
> 回复这个 https://github.com/IGinX-THU/IGinX/pull/424#discussion_r1746964855
> 不知道为什么不能直接回复
> ![image](https://github.com/user-attachments/assets/5825e019-9c85-479b-ac13-9136ca15b743)

这部分测试仅用于 windows 下原filesystem 非 dummy 功能的测试（原Filesystem写入功能强依赖文件路径的格式，所以需要单独处理），现在这部分代码（原filesystem 非 dummy 功能）已经不再使用，所以这部分处理特例的测试也相应删除。

2024-09-09 08:38 UTC, aqni commented
需要修改仓库设置，将 parquet 和 filesystem 的检查要求删除，将 filestore 的检查要求加入

2024-09-11 05:41 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -      String query = "SELECT _:@#$~^{} FROM _:@#$~^{};";
cn.edu.tsinghua.iginx.integration.controller.Controller.writeRowsData 将数据同时写入 dummy 与非 dummy 后续测试将会同时读取 dummy 与非 dummy。

2024-09-14 06:09 UTC, merged