fix(core): float cast to double
IGinX-THU/IGinX pull request #430
Opened 2024-08-22 08:01 UTC by jzl18thu

java中float类型直接隐式转换成double类型时会多出很多小数位，使用 `BigDecimal`类进行处理。

2024-08-30 02:48 UTC, shinyano commented
除了IoT以外，其他引擎需要增加测试吗？目前所有引擎的dummy测试公共部分只有LONG，DOUBLE类型

2024-09-01 13:31 UTC, jzl18thu commented
> 除了IoT以外，其他引擎需要增加测试吗？目前所有引擎的dummy测试公共部分只有LONG，DOUBLE类型

增加了pg和mysql的float类型测试

2024-09-02 09:04 UTC, zhuyuqing requested changes
能否把Redis，parquet，Mongodb也加上？

2024-09-02 13:56 UTC, jzl18thu commented
> 能否把Redis，parquet，Mongodb也加上？

parquet测试已增加，需先合并PR #424

2024-09-14 07:22 UTC, merged