fix: sql syntax of user is missed
IGinX-THU/IGinX pull request #433
Opened 2024-08-22 10:05 UTC by aqni

- 根据之前的 commit 补全 SQL 定义
- 根据之前的 commit 补全 Thrift 定义
- 根据之前的 commit 补全“SQL 语法树解析 -> 执行语句”的构建过程
- 补全 Session 实现
- 补全客户端实现
- 根据用户手册演示内容添加一个简单的测试

2024-08-28 02:52 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/auth/UserPermissionIT.java
> +  public void testUserGuideSample() throws SessionException {
可以增加修改密码的测试？

2024-08-28 03:43 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/auth/UserPermissionIT.java
> +  public void testUserGuideSample() throws SessionException {
增加了修改密码的测试

2024-08-29 09:07 UTC, jzl18thu requested changes

2024-08-29 09:07 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/ChangePasswordStatement.java
> +  private String password;
username和password可以设置为final，下同

2024-08-30 02:35 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/ChangePasswordStatement.java
> +  private String password;
已改

2024-08-30 13:53 UTC, jzl18thu approved these changes

2024-08-31 06:44 UTC, merged