feat(core): sql support case when expression
IGinX-THU/IGinX pull request #436
Opened 2024-08-26 03:44 UTC by jzl18thu

- SQL语句支持使用`case when`
- 优化混合选取列名以及UDTF的语句 `select a, cos(a) from test;` 的解析，避免生成`join by key`算子。

2024-08-30 02:43 UTC, shinyano approved these changes

2024-09-02 09:21 UTC, zhuyuqing requested changes

2024-09-02 09:21 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/ExprUtils.java
> +        throw new RuntimeException(e);
一般不要直接抛RuntimeException

2024-09-02 09:21 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/ExprUtils.java
>        throw new RuntimeException("only row mapping function can be used in expr");
这属于语法错误吗？是否可以定义一个类似于“语法错误”的异常？

2024-09-02 14:19 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/ExprUtils.java
>        throw new RuntimeException("only row mapping function can be used in expr");
是语法错误，抛出InvalidOperatorParameterException异常

2024-09-02 14:19 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/ExprUtils.java
> +        throw new RuntimeException(e);
已修改

2024-09-03 07:21 UTC, merged