fix(udf): use thread pool to execute python tasks
IGinX-THU/IGinX pull request #454
Opened 2024-09-21 10:34 UTC by shinyano

# Whats wrong:
Python task should be executed on seperated threads because Pemja erases `PyThreadState` every time a `PythonInterpreter(java)` got closed. Large python modules like `PyTorch` depends on thread-related information, and the information would get lost if `PyThreadState` got cleared.

## Fix:
Create a thread pool for every python UDF and invoke python in seperated threads.

**NOTE**: We don't need to create thread pools for transform tasks because the transform jobs are running on seperated threads already.

2024-10-05 06:21 UTC, zhuyuqing requested changes

2024-10-05 06:21 UTC, zhuyuqing commented on test/src/test/resources/udf/tensor_test.py
> +    测试用的UDF，注意调用时data只能有一列
函数里基本没有使用data里的值，只是使用了它的列头？因此，只需要data有至少一列，而不是只能有一列吧？

2024-10-05 06:21 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/pool/InterpreterThreadPoolExecutor.java
> +  protected void beforeExecute(Thread t, Runnable r) {
所以，现在是每个Java执行线程，对应一个Python解释器——代价很高？
多个Java线程共享一个Python解释器是如何影响pemja里面的变量的？
不能有更多的共享吗？

2024-10-05 06:21 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/pool/InterpreterThreadPoolExecutor.java
> +  protected void beforeExecute(Thread t, Runnable r) {
Java的执行线程是在多条语句执行中共享的，执行线程池会保持不变，所以解释器池也不变
但是，都是多条语句共享争解释器，现在的实现方法，跟原来的方法有什么本质差别吗？

2024-10-06 14:34 UTC, shinyano commented on test/src/test/resources/udf/tensor_test.py
> +    测试用的UDF，注意调用时data只能有一列
多列的时候，reorder里要求UDF返回的列名会与现在的写法返回的不一样，导致数据列被过滤掉

2024-10-06 14:48 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/pool/InterpreterThreadPoolExecutor.java
> +  protected void beforeExecute(Thread t, Runnable r) {
原来的方法有两点问题：
1. 多个UDF虽然各自有五个interpreter，但都在同一个java线程，一旦一个interpreter被关闭（仅在删除UDF时），解释器的线程信息就会被破坏，其他UDF也会受影响。
2. 同一个线程中建立多个interpreter时，就算不关闭任何一个interpreter，tensor运行也会受影响，可能是因为线程资源占用的原因

现在的方法：每个UDF各自有一个线程池，每个线程与一个interpreter绑定，线程被初始化的时候就新建一个interpreter，线程被销毁时这个interpreter才被关闭，这种一一对应的做法也是比较符合python thread模式的。对于原来方法的修改在于：
1. 每个UDF在不同线程上，关闭一个UDF不会影响其他UDF
2. 不会在同一个线程中建立多个interpreter，每次复用同一个interpreter
如果要再减少资源占用的话，可以考虑不给每个UDF一个线程池，通过加载和卸载python模块来删除UDF，需要试一下

2024-12-01 08:56 UTC, zhuyuqing requested changes

2024-12-01 08:56 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/StorageManager.java
> +      if (!storageMap.containsKey(id)) {
为啥这里不需要测试连接了呢？

2024-12-01 08:56 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +        PythonInterpreterConfig.newBuilder().setPythonExec(PythonCMD).addPythonPaths(PATH).build();
之前看这个路径可能会加载很多次，可以先判断是否存在，再决定是否再次增加

2024-12-01 08:56 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDAF.java
> +  public PyUDAF(String funcName, String moduleName, String className) {
原来为啥可以不要className，现在咱们为啥需要className了？

2024-12-01 08:56 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +  public void tensorUDFTest() {
Good test!

2024-12-02 08:44 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDF.java
> +      // 由于多个UDF共享interpreter，因此使用独特的对象名
原先的udf不会共享interpreter，每个udf各自有五个interpreter实例，这五个interpreter的本地变量是不共享的，但它们会共享一些与线程绑定的资源，这也是torch使用产生bug的原因；

删除UDF时，删除的仅是该UDF对应的模块，它的删除不会对其他UDF产生影响，如果已有的UDF之间有import冲突的话，那么在初始化和运行的时候就会发现了。但删除模块还没办法删除它依赖的库，可能会造成臃肿，后续注册的UDF的依赖如果和这些库存在版本冲突的话可能运行出错

2024-12-12 01:53 UTC, zhuyuqing requested changes

2024-12-12 01:53 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +  @Ignore
为啥Ignore掉？测试不过吗？

2024-12-12 01:53 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +  @Ignore
为啥Ignore掉？测试不过吗？

2024-12-14 01:33 UTC, merged