fix(MAX_HEAP_SIZE): set max heap siez max(min(1/2 ram, 1024MB), min(1…
IGinX-THU/IGinX pull request #456
Opened 2024-09-25 06:06 UTC by ziyuzhao-zzy

…/4 ram, 64GB))

2024-09-27 07:20 UTC, shinyano commented on core/src/assembly/resources/sbin/start_iginx.bat
> +set /a quarter_=%half_%/4
quarter 为什么是 half/4 ？不应该跟.sh一样是 half/2 吗

2024-09-27 07:50 UTC, ziyuzhao-zzy commented on core/src/assembly/resources/sbin/start_iginx.bat
> +set /a quarter_=%half_%/4
对的，应该是/2

2024-10-05 06:24 UTC, zhuyuqing requested changes

2024-10-05 06:24 UTC, zhuyuqing commented on core/src/assembly/resources/sbin/start_iginx.sh
> +  if (( ${half_system_memory_in_mb} > 1024 )); then
这种配置无法将内存资源用全，这个PR的目的就是不将内存资源限制到1024吗？

2024-10-05 06:24 UTC, zhuyuqing commented on core/src/assembly/resources/sbin/start_iginx.bat
> +if ["%half_%"] GTR ["1024"] set half_=1024
这种配置无法将内存资源用全，这个PR的目的就是不将内存资源限制到1024吗？

2024-10-11 02:06 UTC, zhuyuqing requested changes

2024-10-11 02:06 UTC, zhuyuqing commented on core/src/assembly/resources/sbin/start_iginx.bat
> +set /a max_ratio=50
既然是ratio，那就将这个脚本与sh脚本写成一致的。

2024-10-11 02:06 UTC, zhuyuqing commented on core/src/assembly/resources/sbin/start_iginx.bat
> +@REM set /a half_=%system_memory_in_mb%/2
注释的代码都去掉

2024-10-11 02:06 UTC, zhuyuqing commented on core/src/assembly/resources/sbin/start_iginx.sh
>    MAX_HEAP_SIZE=${max_heap_size_in_mb}M
上次讨论的时候，讲过，应该还有个xms吧，应当也允许用户设置，默认值与xmx一样

2024-10-14 01:43 UTC, merged