feat(sql): auto increment sequence & alter key
IGinX-THU/IGinX pull request #458
Opened 2024-09-30 03:53 UTC by jzl18thu

2024-10-05 06:39 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -    errClause = "SELECT 1 * 2 FROM test;";
这条语句现在在IGinX中执行会产生什么样的结果？

2024-10-05 06:39 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Row.java
> +  public static final long NON_EXISTED_KEY = Long.MIN_VALUE;
点赞~

2024-10-07 06:19 UTC, jzl18thu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> -    errClause = "SELECT 1 * 2 FROM test;";
可以正常执行，每行结果都是2，行数与test.*的行数相同

2024-10-09 02:30 UTC, Yihao-Xu requested changes

2024-10-09 02:30 UTC, Yihao-Xu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownAddSchemaPrefixRule.java
> +
我看Key Expression以及下面的Sequence Expression都有column name，这个columnName是可以被add Schema Prefix的吗？如果是的话，照着上面对BaseExpression的操作写一下，在谓词下推过addSchemaPrefix的时候将prefix去掉。

2024-10-09 02:30 UTC, Yihao-Xu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownRenameRule.java
> +          public void visit(SequenceExpression expression) {}
这里跟上面一样，如果column name可以被 rename，那就仿照对base expression的处理写一下

2024-10-09 12:25 UTC, jzl18thu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownAddSchemaPrefixRule.java
> +
不是的，不能被被addSchemaPrefix，KeyExpression是指把key列降级为普通列，SequenceExpression是指生成一个自增序列，他们的columnName是为了在IGinX内部区分未进行重命名的这些列，类似于之前的mark和case when

2024-10-09 12:31 UTC, jzl18thu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownRenameRule.java
> +          public void visit(SequenceExpression expression) {}
KeyExpression和SequenceExpression不会出现在ExprFilter里

2024-10-10 17:13 UTC, Yihao-Xu requested changes

2024-10-10 17:13 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Header.java
> +  public Pair<Header, Integer> renamedHeader(
前面多处都用到了这里的返回值的pair.k = -1来做判断条件，这里写一下注释，说明返回值的-1代表什么吧，不然每次读代码都比较困难

2024-10-11 03:51 UTC, jzl18thu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Header.java
> +  public Pair<Header, Integer> renamedHeader(
colIndex是需要升级为key列的field的下标，等于-1表示没有列需要升级成key列

2024-10-11 07:35 UTC, Yihao-Xu approved these changes

2024-10-11 07:52 UTC, merged