fix(core): get real local ip
IGinX-THU/IGinX pull request #485
Opened 2024-10-30 08:08 UTC by shinyano

## What's wrong
When using `0.0.0.0` in config for iginx listening ip, it displays `0.0.0.0` as it's ip address which is not appropriate. 

## fix
If ip is set to `0.0.0.0`, find the real local ip.

2024-11-14 09:02 UTC, zhuyuqing requested changes

2024-11-14 10:13 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/TransformTaskMeta.java
> +  private Set<Pair<String, Integer>> ipPortSet;
是的，transform函数在同一IP，同一端口，也就是同一个iginx节点上，应该只被注册一次。后面的containsIpPort()函数检查的是ip和端口的值是否重复，不过我发现应该在addIpPort()的时候先进行重复性的检查

2024-11-15 08:38 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
> +    // 当设置监听端口为0.0.0.0，找本机IP地址
如果配置文件不写0.0.0.0，就使用配置文件里的ip；如果发现是0.0.0.0，就优先找内网ip，找不到的话再找外网ip。已添加测试，使用session测试获得的ip和端口是否正确

2024-11-15 08:38 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/other/UDFPathIT.java
> +    tools.isUDFsRegistered(UDFNameList);
已添加测试

2024-11-15 08:38 UTC, shinyano commented on shared/src/test/java/cn/edu/tsinghua/iginx/utils/HostUtilsTest.java
> +    System.out.println(ip);
已修改

2024-11-15 08:38 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/other/UDFPathIT.java
> +    List<String> UDFNameList;
已修改

2024-11-15 08:38 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHRegressionMainIT.java
> +import org.junit.*;
已修改

2024-11-23 13:29 UTC, zhuyuqing approved these changes

2024-11-23 13:30 UTC, merged