feat(test): change action to open all optimizer and close optimizer
IGinX-THU/IGinX pull request #493
Opened 2024-11-07 03:26 UTC by Yihao-Xu

将action中原本为打开pushdown和关闭pushdown改为“Optimize全打开”和“Optimzier全关闭”两种测试场景。
现在默认状态下config中的所有rule和enable pushdown都是开启状态。
修改了部分SQLSessionIT逻辑和结果，来适应rule全开启的状态。

2024-12-11 07:45 UTC, Yihao-Xu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/Rule.java
Integer.Max_VALUE作为默认优先级我认为不合适，默认优先级应该是一个零点，我如果按Integer.Max_VALUE作为默认零点，那某些优先规则的优先级就是Integer.MaxValue-1,某些后置规则的优先级就是Integer.MaxValue+1,不如0作为零点直观。

2024-12-11 07:48 UTC, Yihao-Xu commented on .github/workflows/tpc-h.yml
> +                default: '["InfluxDB", "FileSystem", "PostgreSQL", "Redis", "MongoDB", "MySQL"]'
我们部分谓词下推到底下时会很长，IOTDB在这种情况下会卡死，无法通过测试，因为是IoTDB的问题，经过讨论，带优化器的tpch就不再测试IoTDB了

2024-12-12 08:01 UTC, aqni approved these changes

2024-12-12 08:02 UTC, aqni commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/Rule.java
改回0

2024-12-13 05:59 UTC, aqni requested changes
把评论中提到的进行修改

2024-12-16 01:07 UTC, zhuyuqing commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/Rule.java
优先级与数值的关系，加注释

2024-12-16 05:58 UTC, aqni approved these changes

2024-12-16 06:22 UTC, aqni commented
以前的测试没有减少

2024-12-16 07:31 UTC, merged