feat(ci): test free-threading python 3.13.0
IGinX-THU/IGinX pull request #494
Opened 2024-11-10 18:29 UTC by shinyano

## New tests:
Add tests for `python3.13t` on:
- win & mac & linux
- iotdb & filesystem

## Note:
The `testAddStorageEngine` test in `PySessionIT` is skipped because it relies on `fastparquet` module which does not support python 3.13 yet

2024-11-14 08:47 UTC, zhuyuqing requested changes

2024-11-14 08:47 UTC, zhuyuqing commented on .github/actions/service/ftPython/action.yml
> +name: "Install_Free-thread_Python"
把这个ftPython名字改成完整的名称吧，如freeThreadPython

2024-11-14 08:47 UTC, zhuyuqing commented on .github/actions/service/ftPython/action.yml
> +              <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
为啥mac这么神奇地在安装时还出现XML的内容？

2024-11-14 08:47 UTC, zhuyuqing commented on .github/workflows/free-thread-test.yml
> +                description: "The database to run the test on"
为啥选定仅在这2个数据源执行？

2024-11-14 08:47 UTC, zhuyuqing commented on .github/actions/service/pemjaxInstall/action.yml
> +name: "install-pemjax"
如果仅安装了这个使用13t的pemjax版本，在不使用13t的情况下，还能跑吗

2024-11-14 09:50 UTC, shinyano commented on .github/actions/service/ftPython/action.yml
> +              <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
这里是配置安装选项，设置安装所有的包，包括free-threading解释器，因为不能使用GUI所以使用了配置文件

2024-11-14 09:51 UTC, shinyano commented on .github/workflows/free-thread-test.yml
> +                description: "The database to run the test on"
参考remote test的选择，选了一个需要连接的iotdb，和一个本地的filesystem

2024-11-14 09:53 UTC, shinyano commented on .github/actions/service/pemjaxInstall/action.yml
> +name: "install-pemjax"
现在action都有自带的python，如果不用13t的话就是用它自带的那个python版本

2024-11-14 09:54 UTC, shinyano commented on .github/actions/service/ftPython/action.yml
> +name: "Install_Free-thread_Python"
已修改

2025-01-15 05:55 UTC, aqni commented on .github/actions/confWriter/action.yml
> +              if [[ "${{ inputs.use-free-thread-python }}" == "true" && "$RUNNER_OS" != "Windows" ]]; then
这里建议写成 if 中嵌套 if，可读性更好
```
if [[ "${{ inputs.use-free-thread-python }}" == "true" ]]; then
  if [ "$RUNNER_OS" == "Windows" ]; then

  else

  fi
else
  if [ "$RUNNER_OS" == "Windows" ]; then
    pythonCMD=python
  else
    pythonCMD=python3
  fi
fi
```

2025-01-15 05:55 UTC, aqni commented on .github/workflows/DB-CE.yml
> +            IGINX_CONDA_ENV: "iginxEnv"
尽可能使用参数吧，用环境变量不容易维护，后续修改的时候容易忽略

2025-01-15 05:55 UTC, aqni commented on .github/workflows/DB-CE.yml
> +              shell: bash -el {0}
这么改是为了解决什么问题？

2025-01-15 05:55 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +      LOGGER.debug("main thread: python site path: {}", sitePath);
建议使用 LOGGER.isDebug 进行分支判断，以避免在未启用 debug 日志时引入额外开销

2025-01-15 05:55 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ShellRunner.java
> +      throw new Exception("run command failed: " + e.getMessage());
最好使用一个具体 Exception子类

2025-01-15 05:55 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/PySessionIT.java
> +      return;
建议使用 Assume.assume() 函数来跳过不支持的测试，而不是 if(condition) {return;}

2025-01-15 05:55 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +      return;
建议使用 Assume.assume() 函数来跳过不支持的测试，而不是 if(condition) {return;}

2025-01-15 16:47 UTC, shinyano commented on .github/workflows/DB-CE.yml
> +              shell: bash -el {0}
-l 登录模式下，才可使用conda

2025-01-15 17:07 UTC, shinyano commented on .github/actions/confWriter/action.yml
> +              if [[ "${{ inputs.use-free-thread-python }}" == "true" && "$RUNNER_OS" != "Windows" ]]; then
改了

2025-01-15 17:07 UTC, shinyano commented on .github/workflows/DB-CE.yml
> +            IGINX_CONDA_ENV: "iginxEnv"
改了

2025-01-15 17:07 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +      LOGGER.debug("main thread: python site path: {}", sitePath);
改了

2025-01-15 17:08 UTC, shinyano commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ShellRunner.java
> +      throw new Exception("run command failed: " + e.getMessage());
直接抛出吧，看了一下感觉没包装必要

2025-01-15 17:08 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
> +      return;
改了

2025-01-16 02:49 UTC, aqni approved these changes

2025-01-17 02:09 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/utils/SQLTestTools.java
> +        command[0] = "C:/Program Files/Git/bin/bash.exe";
这个为啥写的这么死？

2025-01-17 02:16 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/utils/SQLTestTools.java
> +        command[0] = "C:/Program Files/Git/bin/bash.exe";
Github测试专用，暂时折中

2025-01-17 02:17 UTC, zhuyuqing approved these changes

2025-01-17 02:18 UTC, zhuyuqing commented on .github/workflows/free-thread-test.yml
> +name: "Free-threading Python Test"
测试加上后，再重跑一下测试~

2025-01-20 03:51 UTC, merged