Fix it structure
IGinX-THU/IGinX pull request #53
Opened 2023-03-27 06:54 UTC by RemHero

2023-03-31 01:35 UTC, zhuyuqing requested changes
为每个workflow增加一个输出，将已经跑过的测试组合信息，都打印输出出来，以便检查

2023-03-31 07:41 UTC, zhuyuqing commented
> # 扩展原有测试
> ### 目的
> 先前的 Pr 包含了原有的所有测试，但是之前没有的测试，有些数据库没有配置SessionIT以及SessionPoolIT，这部分测试不会被被测试，也仅限SessionIT没有被测试，但是对于通用测试，如TagIT、UDFIT等，都已经对 IoTDB12、Parquet、InfluxDB进行测试。 此 Pr 对所有数据库进行所有IT测试，除非该数据库不支持某些特性。
> 
> ### 修改部分
> 1、只需要将原有的 testConfig 中的测试修改为基础测试的原名，即将 {}BaseSessionIT 改为 BaseSession，不依赖于底层数据库 2、将非代码文件移入 resource 3、修复了BaseSessionIT、BaseSessionPoolIT中session被关闭等bug、在SQLSessionIT、SQLSessionPoolIT、TagIT中加入了对应的测试选项 4、优化了测试结构

点赞！~\(≧▽≦)/~

2023-04-02 03:43 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/iotdb/IoTDBHistoryDataGenerator.java
>  public class IoTDBHistoryDataGenerator extends BaseHistoryDataGenerator {
把这个类的名字改成IoTDB12HistoryDataGenerator吧

2023-04-02 03:46 UTC, SolomonAnn commented on test/src/test/resources/testConfig.properties
> +test-list=SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,TransformIT,UDFIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT
少了CompactionIT

2023-04-02 03:49 UTC, SolomonAnn commented on test/src/test/resources/testConfig.properties
>  IoTDB12-config=isAbleToClearData=true,isAbleToDelete=true,isAbleToShowTimeSeries=true,isSupportSpecialPath=true,isSupportTagKV=true
为什么除了IoTDB，其他的都不能clear data，不是能delete就能clear data吗？

2023-04-02 03:51 UTC, SolomonAnn commented on .github/workflows/DB-CE.yml
> +  FUNCTEST: TagIT,RestIT,TransformIT,UDFIT,RestAnnotationIT,SQLSessionIT,SQLSessionPoolIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT
少了CompactionIT

2023-04-03 01:03 UTC, iznauy approved these changes

2023-04-03 01:03 UTC, iznauy commented on .github/actions/confWriter/action.yml
> +
不必要的变更

2023-04-03 01:06 UTC, iznauy commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseHistoryDataGenerator.java
> +    }
这里为啥不都实现成抽象方法 public abstract void xxxx() throws Exception

2023-04-03 02:40 UTC, SolomonAnn commented on .github/actions/confWriter/action.yml
> +        echo "${{inputs.Test-Way}}" > ${GITHUB_WORKSPACE}/test/src/test/java/cn/edu/tsinghua/iginx/integration/ifScaleOutIn.txt
临时文件也放在resource目录下吧

2023-04-03 02:42 UTC, SolomonAnn commented on .github/workflows/DB-CE.yml
> +  InfluxDBFUNCTEST: RestAnnotationIT
确认过InfluxDB只能支持这一个测试吗？为什么不能支持其他测试呢？

2023-04-03 02:48 UTC, SolomonAnn commented on .github/workflows/DB-CE.yml
> +            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#testPrefixAndRemoveHistoryDataSource -DfailIfNoTests=false
InfluxDB不支持testPrefixAndRemoveHistoryDataSource测试吗？

2023-04-04 06:54 UTC, RemHero commented on test/src/test/resources/testConfig.properties
>  IoTDB12-config=isAbleToClearData=true,isAbleToDelete=true,isAbleToShowTimeSeries=true,isSupportSpecialPath=true,isSupportTagKV=true
已改

2023-04-04 06:58 UTC, RemHero commented on .github/workflows/DB-CE.yml
> +  InfluxDBFUNCTEST: RestAnnotationIT
有其他pr修改influxdb

2023-04-04 09:04 UTC, zhuyuqing submitted a review, later dismissed

2023-04-04 09:04 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/tag/TagIT.java
> +        this.ifScaleOutIn = conf.ifScaleOutIn();
常见规范是isScaling, isClearingData吧？
你看中间那个，isAbleToDelete，把这些一致起来吧？

2023-04-04 09:04 UTC, zhuyuqing commented on test/src/test/resources/testConfig.properties
> +test-list=SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,TransformIT,UDFIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT,CompactionIT
为啥有了test-list，还需要下面的？
数据不是可以配置属性，然后自动匹配哪些测试可用吗？

2023-04-04 09:04 UTC, zhuyuqing commented on test/src/test/resources/testConfig.properties
> +influxdb-test-list=SQLSessionIT,SQLSessionPoolIT,RestAnnotationIT,TransformIT,BaseSessionIT,BaseSessionPoolIT,CompactionIT
为啥不支持UDFIT

2023-04-04 09:04 UTC, zhuyuqing commented on test/src/test/resources/testConfig.properties
> +mongodb-test-list=SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,UDFIT,TransformIT,SessionV2IT,CompactionIT
parquet和mongodb为啥不用支持BaseSessionIT,BaseSessionPoolIT？

2023-04-04 09:04 UTC, zhuyuqing commented on thrift/pom.xml
> +</project>
为啥会有这种修改？。。。

2023-04-04 10:17 UTC, RemHero commented on test/src/test/resources/testConfig.properties
> +mongodb-test-list=SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,UDFIT,TransformIT,SessionV2IT,CompactionIT
因为这两个问题会放在后续pr中修补，这个pr是为了修整测试结构

2023-04-04 10:17 UTC, RemHero commented on test/src/test/resources/testConfig.properties
> +influxdb-test-list=SQLSessionIT,SQLSessionPoolIT,RestAnnotationIT,TransformIT,BaseSessionIT,BaseSessionPoolIT,CompactionIT
因为这个问题会放在influxdb的pr中修补，这个pr是为了修整测试结构

2023-04-04 10:20 UTC, RemHero commented on test/src/test/resources/testConfig.properties
> +test-list=SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,TransformIT,UDFIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT,CompactionIT
每个数据库有test-list是为了更灵活的匹配测试，比如influxdb不能对sessionV2IT进行测试，因为其不支持double数据结构。一些数据库加进来可以选择性测试，直到所有测试全部通过

2023-04-04 10:21 UTC, RemHero commented on core/pom.xml
> -</project>
参考https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b，应该是要求在文末加入新行

2023-04-04 10:33 UTC, RemHero commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/tag/TagIT.java
> +        this.ifScaleOutIn = conf.ifScaleOutIn();
已改

2023-05-08 02:51 UTC, SolomonAnn commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBStorage.java
>              filterStr.append(')');
如果上面的if语句判定为false，那么filterStr就会以两个")"结尾

2023-05-08 02:54 UTC, SolomonAnn commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBStorage.java
> +                return new TaskExecuteResult(
为什么这里直接return，而不是continue，是因为所有pattern对应的bucketName都一样吗？

2023-05-08 03:05 UTC, SolomonAnn commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/query/entity/InfluxDBQueryRowStream.java
> +            filterMap[i] = filterList.get(i);
filterMap和filterList好像是完全等价的

2023-05-08 06:38 UTC, SolomonAnn commented on .github/workflows/DB-CE.yml
> +    InfluxDBFUNCTEST: NewSessionIT,SQLCompareIT,TagIT,RestIT,TransformIT,UDFIT,RestAnnotationIT,SQLSessionIT,SQLSessionPoolIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT,CompactionIT,TimePrecisionIT
这3个FUNCTEST没区别啊

2023-05-08 06:43 UTC, SolomonAnn commented on .github/workflows/unit-mds.yml
> +            #  run: mvn test -q -Dtest=IMetaManagerTest -DfailIfNoTests=false
ETCD不能执行IMetaManagerTest吗？

2023-05-08 07:05 UTC, SolomonAnn commented on test/README.md
> +  - 目前测试的包括`SQLSessionIT,SQLSessionPoolIT,TagIT,RestAnnotationIT,RestIT,TransformIT,UDFIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT`
不完整，少CompactionIT和TimePrecisionIT

2023-05-08 07:05 UTC, SolomonAnn commented on test/README.md
> +
少formatChecker

2023-05-08 07:19 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/ConfLoder.java
> +    private String IFSCALEOUTIN = "./src/test/resources/ifScaleOutIn.txt";
其他文件里这个参数都叫isScaling，全局搜一下把ifScaleOutIn都改成isScaling吧

2023-05-08 07:51 UTC, RemHero commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBStorage.java
>              filterStr.append(')');
这个没问题，是匹配的

2023-05-08 08:02 UTC, RemHero commented on dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/query/entity/InfluxDBQueryRowStream.java
> +            filterMap[i] = filterList.get(i);
fixed

2023-05-08 08:03 UTC, RemHero commented on .github/workflows/DB-CE.yml
> +    InfluxDBFUNCTEST: NewSessionIT,SQLCompareIT,TagIT,RestIT,TransformIT,UDFIT,RestAnnotationIT,SQLSessionIT,SQLSessionPoolIT,SessionV2IT,BaseSessionIT,BaseSessionPoolIT,CompactionIT,TimePrecisionIT
这个为了后面的结构简单而设计的，也好让不同数据库针对不同测试

2023-05-08 08:07 UTC, RemHero commented on test/src/test/resources/testConfig.properties
> +InfluxDB-config=isAbleToClearData=true,isAbleToDelete=false,isAbleToShowTimeSeries=true,isSupportSpecialPath=false
是的，之前有一个版本测试了，都不支持

2023-05-15 08:51 UTC, SolomonAnn approved these changes

2023-05-16 07:12 UTC, Cauchy-NY approved these changes

2023-05-16 07:13 UTC, SolomonAnn approved these changes

2023-05-17 03:07 UTC, SolomonAnn approved these changes

2023-05-17 03:09 UTC, Cauchy-NY approved these changes

2023-05-17 06:53 UTC, merged