feat: add vectordb datasource
IGinX-THU/IGinX pull request #530
Opened 2024-12-12 04:13 UTC by reamofchaos

2024-12-12 07:46 UTC, SolomonAnn commented
MilvusConnectPool、MilvusClientPool、MilvusClientPool、MilvusClient，这些类名看起来很迷惑，是否能更明确一点，至少每个类加个注释

2024-12-12 07:48 UTC, SolomonAnn commented on dataSource/vectordb/src/main/java/cn/edu/tsinghua/iginx/vectordb/MilvusStorage.java
> +      e.printStackTrace();
改成日志输出，主代码里不应出现e.printStackTrace()

2024-12-12 07:48 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBHistoryDataGenerator.java
> +              added =
不太确定valuesList是否以数组的形式写入了向量字段？建议写入之后直接查milvus确定写入无误

2024-12-12 09:49 UTC, reamofchaos commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/StorageEngineClassLoader.java
> +    if (clazz != null) {
milvus java sdk内部用到了Class.forname加载类，有的类不是必须的，在这里会返回空值，如果抛出异常，vectordb模块就加载不了

2024-12-12 09:51 UTC, reamofchaos commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ShellRunner.java
> +  public void runShellCommandOnWindows(String command) throws Exception {
这个新方法只有在vectordb且为windows系统时使用，做的特殊处理以区分其它模块，不影响其它模块功能

2024-12-13 08:56 UTC, SolomonAnn commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBHistoryDataGenerator.java
> +    writeHistoryData(
需增加字符串主键相关测试

2024-12-16 07:21 UTC, zhuyuqing commented on .github/workflows/DB-CE.yml
> +        timeout-minutes: 360
300

2024-12-20 12:54 UTC, reamofchaos commented
workflows中未配置和执行vectordb的tpc-h测试
DB-CE测试中跳过了vectordb在ubuntu-latest和macos-latest平台上的测试

2024-12-23 07:44 UTC, aqni requested changes

2024-12-23 07:44 UTC, aqni commented on .github/actions/dbRunner/action.yml
> +              statements: s/^#storageEngineList=192.168.106.2#19530/storageEngineList=192.168.106.2#19530/g
192.168.106.2 是固定的吗，始终不会发生变化吗

2024-12-23 07:44 UTC, aqni commented on dataSource/pom.xml
> +                                    <delete file="target/${project.artifactId}-${project.version}/driver/${project.artifactId}/milvus-sdk-java-${milvus.version}.jar"/>
为什么需要删除这个 jar 包，copy 时新的 jar 包不会正确覆盖原文件吗

2024-12-23 07:44 UTC, aqni commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/ShellRunner.java
> +        builder.command(BASH_PATH, command);
这里出于什么原因进行修改？

2024-12-23 07:44 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBCapacityExpansionIT.java
> +  protected void testQuerySpecialHistoryData() {
这里只验证了 float data 一种类型。
至少还需要验证：
1. vectordb 的更多数据类型，尤其是向量类型
2. 字符串/数字做主键的两种情况是否正确
3. 复杂 filter 的翻译在 dummy 查询中是否正确
4. 动态 field 的查询，以及filter的翻译
5. dummy 数据在 show columns 语句是否正确

可以参考 mongodb 和 filesystem

2024-12-23 08:09 UTC, aqni commented
![微信图片_20241223160630](https://github.com/user-attachments/assets/32f89eb7-9db4-4c84-98c1-532726360c93)
vectordb 的测试有些需要不在macos上测试或者延长超时时间，可以使用类似这样的方式修改 standart-test-suite.yml 和 full-test-suite.yml

2024-12-26 05:06 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBCapacityExpansionIT.java
> +        Arrays.asList(Arrays.asList(22.33F, "[1.0, 2.0]"), Arrays.asList(44.55F, "[3.0, 4.0]"));
看起来是将vector以json的形式转换为字符串，这种转换朱老师是否认可？

2024-12-26 05:06 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBCapacityExpansionIT.java
> +  private void testFilter() {
是否可以添加使用多个列进行过滤的测试？

2024-12-26 06:11 UTC, reamofchaos commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBCapacityExpansionIT.java
> +        Arrays.asList(Arrays.asList(22.33F, "[1.0, 2.0]"), Arrays.asList(44.55F, "[3.0, 4.0]"));
因为现有的DataType只有BOOLEAN，INTEGER，LONG，FLOAT，DOUBLE，BINARY几个基本类型，没有数组类型，因此将向量字段转成了数组以字符串显示，如有更合适的方式配合修改

2024-12-26 06:12 UTC, reamofchaos commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/vectordb/VectorDBCapacityExpansionIT.java
> +  private void testFilter() {
已经添加

2025-01-13 08:53 UTC, aqni commented on dataSource/vectordb/src/main/java/cn/edu/tsinghua/iginx/vectordb/tools/MilvusClientUtils.java
> +                      .topK(1)
如果有许多相同的向量，在搜索时应当作何处理？ 在这种情况下选择 top1 ，朱老师是否接受。

2025-01-13 08:53 UTC, aqni commented on dataSource/vectordb/src/main/java/cn/edu/tsinghua/iginx/vectordb/tools/MilvusClientUtils.java
> +              FloatVec queryVector = new FloatVec(JsonUtils.stringToArray(value));
如果 JsonUtils.stringToArray(value) 由于格式不符返回 null，会不会导致查询失败？

2025-01-13 14:09 UTC, reamofchaos commented on dataSource/vectordb/src/main/java/cn/edu/tsinghua/iginx/vectordb/tools/MilvusClientUtils.java
> +                      .topK(1)
已经修改为topk可以配置，只返回向量与搜索值完全匹配的记录

2025-01-14 06:03 UTC, aqni approved these changes

2025-01-27 11:53 UTC, merged