fix(transform): some fix & refactor
IGinX-THU/IGinX pull request #538
Opened 2024-12-19 10:06 UTC by shinyano

## Feat:
- If re-registered, Python UDFs will be reloaded in transform tasks.
- Show all/idle jobs
```sql
-- show all jobs:
show transform jobs;

-- show idle jobs:
show idle transform jobs;
```
- (wip) On restart, unfinished scheduled transform jobs should be able to start.

## Fix:
- When cancelling finished/closed/failed jobs, correct information is given (e.g. `job with id: xxx has finished/closed/failed.`)
- Add missed new line in result.
- When sql execution fails, transform job fails immediately and print correct error message & source in server log.
- (wip) `yaml` job files' paths should be specified relative to the client, not the server.

TODO: add tests

2024-12-20 07:22 UTC, aqni commented on conf/config.properties
> +defaultScheduledTransformJobDir=transform_jobs
可以通过继承测试验证文件夹内的定时任务是否被导入了吗？

2024-12-20 07:22 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  private static final String PythonCMD = config.getPythonCMD();
这里是否应当去掉 static，config中的 pythonCMD 参数值是否可能变化

2024-12-20 07:22 UTC, aqni commented on thrift/src/main/thrift/rpc.thrift
> +    24: optional map<JobState, list<i64>> jobStateMap
这里出于什么原因，将list改为map？

2024-12-20 07:22 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/TransformIT.java
> +      List<Long> closedJobIds =
是否应当检查map中其他状态是否为空？

2024-12-20 13:08 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  private static final String PythonCMD = config.getPythonCMD();
不会变

2024-12-20 13:08 UTC, shinyano commented on thrift/src/main/thrift/rpc.thrift
> +    24: optional map<JobState, list<i64>> jobStateMap
显示所有状态的job

2024-12-20 13:09 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/TransformIT.java
> +      List<Long> closedJobIds =
无必要，其他测试的job也在

2024-12-21 08:55 UTC, shinyano commented on conf/config.properties
> +defaultScheduledTransformJobDir=transform_jobs
修改和测试移至新pr

2024-12-22 09:30 UTC, zhuyuqing requested changes

2024-12-22 09:30 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  @Getter private final PythonInterpreter interpreter;
突然来这么一下，好突兀，很必要吗？
要不还是改回原来那样吧

2024-12-22 09:30 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      return new ShowEligibleJobStatement(jobState);
存在多种STATUS共存的情况吗？
这些if else if，为啥必须是这样的先后关系？

2024-12-22 09:30 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/transform/driver/PemjaDriver.java
> +    interpreter.exec(String.format("import %s; import importlib", moduleName));
为啥左边的81行，后来可以去掉？原来的作用是？

2024-12-22 09:47 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      return new ShowEligibleJobStatement(jobState);
不会共存，这边的判断没有逻辑顺序，只是按照g4文件里的顺序写了（出于些许的强迫症），idle的位置在created和running之间也和job的状态变化过程比较相符

2024-12-22 09:55 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/transform/driver/PemjaDriver.java
> +    interpreter.exec(String.format("import %s; import importlib", moduleName));
定时任务中可能会用到多个udf，之前的用法是每个udf创建一个interpreter，但这样会造成同一线程上多个interpreter的情况，所以现在改成每个udf都使用一个共享的与线程绑定的interpreter，因此需要使用不同的对象名

2024-12-22 10:04 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
> +      return new ShowEligibleJobStatement(jobState);
不共存的话，这段是不是可以写得更优雅一点啊？一个Status？case switch?

2024-12-22 10:34 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  @Getter private final PythonInterpreter interpreter;
改好了

2024-12-23 00:56 UTC, zhuyuqing approved these changes

2024-12-23 04:54 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  private static final String PythonCMD = config.getPythonCMD();
set config 语句会修改吗

2024-12-23 04:56 UTC, aqni commented on thrift/src/main/thrift/rpc.thrift
> +    24: optional map<JobState, list<i64>> jobStateMap
为什么需要显示所有状态的job？ 函数参数不是指定了仅获取某一种状态的 jobId 吗，这样做相比原来有什么好处？

2024-12-23 05:23 UTC, shinyano commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
> +  private static final String PythonCMD = config.getPythonCMD();
和set config有什么关系

2024-12-23 05:24 UTC, shinyano commented on thrift/src/main/thrift/rpc.thrift
> +    24: optional map<JobState, list<i64>> jobStateMap
新需求，有测试

2024-12-23 07:06 UTC, merged