feat(optimizer): Agg Pushdown Rule
IGinX-THU/IGinX pull request #544
Opened 2024-12-24 08:16 UTC by Yihao-Xu

2025-01-10 03:23 UTC, aqni requested changes

2025-01-10 03:23 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
>                                  case Project:
project 这里可以考虑重构一下，现在这里分支判断过多，函数过长。现在这里又加了这么多内容，可维护性更差了。

2025-01-10 03:23 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Field.java
> +  public Field(String name, String fullName, DataType type, Map<String, String> tags) {
为什么需要用到这个函数，而不是其他构造函数？直接使用函数可能造成 fullName 不按指定规则生成。

2025-01-10 03:23 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/expr/Operator.java
> +  CAL_STAR, // 乘法计算,*，目前只在对接层使用
只在对接层使用应当在对接层使用一个新类，不应当将对接层的修改注入到 core 中

2025-01-10 03:23 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/FunctionParams.java
> +  public void updatePaths() {
可以在用户修改 expression 时顺带修改 path，这样由调用者更新 path 很容易被忽略，导致数据不一致。

2025-01-10 03:23 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/GroupBy.java
> +  public void updateGroupByCols() {
可以在用户修改 expression 时顺带修改 path，这样由调用者更新 path 很容易被忽略，导致数据不一致。

2025-01-10 03:23 UTC, aqni commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/NaivePhysicalOptimizer.java
> +          } else if ((operator.getType() == OperatorType.GroupBy
groupby 和 agg 是两种操作吧，个人认为分成两种情况下推更好

2025-01-10 03:23 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/optimizer/OptimizerIT.java
> +    if (!isOptimizerOpen) {
这些关于 isOptimizerOpen 的判断是不需要的，上面已经判断过 Assume.assumeTrue(isOptimizerOpen)  了

2025-01-10 08:08 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  default boolean isSupportProjectWithAgg(Operator agg, DataArea dataArea, boolean isDummy) {
还有GroupBy

2025-01-10 08:09 UTC, Yihao-Xu commented on .github/workflows/tpc-h.yml
> +                  Set-AggPushDown-OFF: ${{ toJSON(!contains(inputs.agg-pushdown-matrix, matrix.DB-name)) }}
下推如果对接层无法推到数据库中，会产生负优化

2025-01-10 08:11 UTC, Yihao-Xu commented on optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/NaivePhysicalOptimizer.java
> +          } else if ((operator.getType() == OperatorType.GroupBy
但它们用的下推代码都是一样的

2025-01-16 03:10 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  default boolean isSupportProjectWithAgg(Operator agg, DataArea dataArea, boolean isDummy) {
这个可以让用户写在这一个函数的逻辑里，具体的算子和isDummy都已给出足以判断，分成4个接口反而增加了复杂度

2025-01-16 03:11 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/optimizer/OptimizerIT.java
> +    if (!isOptimizerOpen) {
已改

2025-01-16 03:11 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  TaskExecuteResult executeProjectWithAgg(Project project, Operator agg, DataArea dataArea);
已合并

2025-01-16 03:11 UTC, Yihao-Xu commented on conf/config.properties
> +needInitBasicUDFFunctions=true
已修改

2025-01-16 03:25 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/GroupBy.java
> +  public void updateGroupByCols() {
已添加添加相应的set函数，能够set的同时update path

2025-01-16 03:25 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/FunctionParams.java
> +  public void updatePaths() {
已添加添加相应的set函数，能够set的同时update path

2025-01-16 03:48 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/expr/Operator.java
> +  CAL_STAR, // 乘法计算,*，目前只在对接层使用
已修改

2025-01-21 02:36 UTC, aqni commented on .github/workflows/tpc-h.yml
> +                  Set-AggPushDown-OFF: ${{ toJSON(!contains(inputs.agg-pushdown-matrix, matrix.DB-name)) }}
这种状态是存在的，所以也应该测试吧？

2025-01-21 02:42 UTC, Yihao-Xu commented on .github/workflows/tpc-h.yml
> +                  Set-AggPushDown-OFF: ${{ toJSON(!contains(inputs.agg-pushdown-matrix, matrix.DB-name)) }}
tpch在这种负优化的情况过不了测试

2025-01-21 02:44 UTC, aqni commented on .github/workflows/tpc-h.yml
> +                  Set-AggPushDown-OFF: ${{ toJSON(!contains(inputs.agg-pushdown-matrix, matrix.DB-name)) }}
看起来只有 tpch 做了特殊处理，其他测试都照顾到了上面这种情况

2025-01-21 02:45 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  TaskExecuteResult executeProjectWithAgg(Project project, Operator agg, DataArea dataArea);
这个合并后有没有遇到不兼容的问题

2025-01-21 02:49 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  TaskExecuteResult executeProjectWithAgg(Project project, Operator agg, DataArea dataArea);
从测试上看起来好像没什么问题

2025-01-21 02:50 UTC, aqni commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  default boolean isSupportProjectWithAgg(Operator agg, DataArea dataArea, boolean isDummy) {
有的数据库可能不支持同时下推 filter 和 agg（filesystem或者未来的其他对接层），建议至少分两类判断，同时下推 "filter agg" 和只下推 agg

2025-01-21 07:55 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/IStorage.java
> +  default boolean isSupportProjectWithAgg(Operator agg, DataArea dataArea, boolean isDummy) {
已修改

2025-01-22 02:53 UTC, aqni approved these changes

2025-01-24 08:25 UTC, zhuyuqing requested changes

2025-01-24 08:25 UTC, zhuyuqing commented on conf/config.properties
> +# UDF定义文件夹存储路径（相对或绝对），文件夹内的文件需要按以下格式进行编写
冲突解的有问题？

2025-01-24 08:25 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
>                                        operators.size() == 2
确实，代码可读性需要提升，看用什么模式调整一下？

2025-01-24 08:25 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Field.java
> +  public Field(String name, String fullName, DataType type, Map<String, String> tags) {
同问

2025-01-24 08:25 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +        executor.execute(query).equals(expected) || executor.execute(query).equals(expected2));
为啥可以有2种可能结果？因为有或没有优化吗？

2025-01-24 08:25 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +        executor.execute(query).equals(expected) || executor.execute(query).equals(expected2));
好像2个结果没有差别？

2025-01-24 08:25 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +            + "CROSS JOIN max_bonus_outlet AS max ORDER BY ao.outlet;";
这些新加的order by是为了啥？

2025-01-24 08:25 UTC, zhuyuqing commented on .github/actions/confWriter/action.yml
> +        - if: inputs.Set-AggPushDown-OFF=='true'
这个在什么地方用上了吗？~

2025-02-05 01:17 UTC, Yihao-Xu commented on .github/actions/confWriter/action.yml
> +        - if: inputs.Set-AggPushDown-OFF=='true'
AggPushDown是默认开的，但是在tpch中，没有实现agg push down的对接层会产生一定的负优化，导致tpch测试无法通过，因此会在tpch测试中对于没有实现agg push down的对接层关闭该规则。

2025-02-05 01:19 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +            + "CROSS JOIN max_bonus_outlet AS max ORDER BY ao.outlet;";
agg push down之后，group by交给底层连接的数据库去做，group by出来的行顺序各个数据库都是不一样的，所以在这里加一个order by来统一顺序。

2025-02-05 01:34 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Field.java
> +  public Field(String name, String fullName, DataType type, Map<String, String> tags) {
这个是在RelationRowStream里用到了这个函数，因此把它置为public了

2025-02-05 01:35 UTC, Yihao-Xu commented on conf/config.properties
> +# UDF定义文件夹存储路径（相对或绝对），文件夹内的文件需要按以下格式进行编写
已修改

2025-02-05 02:26 UTC, Yihao-Xu commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +        executor.execute(query).equals(expected) || executor.execute(query).equals(expected2));
之前遗留的修改，这是因为pg的sum会统一返回float的结果而增加的判断，现在已经解决了这个问题。
这个可能结果已经删除。

2025-02-05 03:31 UTC, Yihao-Xu commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
>                                        operators.size() == 2
用策略模式和工厂模式进行了重构

2025-02-21 01:50 UTC, zhuyuqing commented on .github/actions/confWriter/action.yml
> +                  sudo sed -i '' 's/ruleBasedOptimizer=NotFilterRemoveRule=on,FragmentPruningByFilterRule=on/ruleBasedOptimizer=NotFilterRemoveRule=on/g' ${{ inputs.Root-Dir-Path }}/core/target/iginx
使用一下叫edit的那个action ，这样不需要分操作系统讨论

2025-02-21 07:47 UTC, Yihao-Xu commented on .github/actions/confWriter/action.yml
> +                  sudo sed -i '' 's/ruleBasedOptimizer=NotFilterRemoveRule=on,FragmentPruningByFilterRule=on/ruleBasedOptimizer=NotFilterRemoveRule=on/g' ${{ inputs.Root-Dir-Path }}/core/target/iginx
已修改

2025-02-21 08:04 UTC, merged