Test/tpch/add warmup
IGinX-THU/IGinX pull request #547
Opened 2024-12-26 05:51 UTC by aqni

2024-12-31 09:35 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHNewIT.java
>        LOGGER.info("No query remain, skip test main branch.");
这里的main branch应该也要相应改下吧

2024-12-31 09:36 UTC, shinyano commented on .github/actions/tpchSingleTest/action.yml
> +              sleep 30
启动IGinX的话，需要30s这么久么

2024-12-31 09:39 UTC, shinyano commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHOldIT.java
>        LOGGER.info("No query remain, skip test new branch.");
捉虫 new branch

2024-12-31 09:41 UTC, shinyano commented on .github/workflows/tpc-h.yml
> +            - name: Run Metadata
这边是改用同一个zk？为啥呢

2024-12-31 09:58 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHNewIT.java
>        LOGGER.info("No query remain, skip test main branch.");
TPCHNewIT中的test测试新分支， TPCHOldIT中的test测试main branch，只是名字发生了变化，没有本质区别。

2024-12-31 09:59 UTC, aqni commented on .github/actions/tpchSingleTest/action.yml
> +              sleep 30
参考了 `.github/scripts/iginx/iginx.sh` 中的超时时间

2024-12-31 10:00 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHOldIT.java
>        LOGGER.info("No query remain, skip test new branch.");
TPCHNewIT中的test测试新分支， TPCHOldIT中的test测试main branch，只是名字发生了变化，没有本质区别。

2024-12-31 10:01 UTC, aqni commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tpch/TPCHOldIT.java
>        LOGGER.info("No query remain, skip test new branch.");
TPCHOldIT 和 TPCHNewIT 中的已改。

2024-12-31 10:03 UTC, shinyano commented on test/src/test/resources/warmup/warmup.sql
> +      FROM (SELECT *FROM *))
要不在 * 和 FROM 之间加个空格吧

2024-12-31 10:05 UTC, aqni commented on .github/workflows/tpc-h.yml
> +            - name: Run Metadata
流程发生了变化，之前每次重新测试不会进行clear data，所以交替测试main和new分支需要分别使用两套 zk 和 db。现在增加了 warmup 流程，必须进行 clear data，所以可以只用一套 zk 和 db。

2024-12-31 10:05 UTC, aqni commented on test/src/test/resources/warmup/warmup.sql
> +      FROM (SELECT *FROM *))
好

2024-12-31 10:09 UTC, shinyano commented on .github/workflows/tpc-h.yml
> +            - name: Run Metadata
用两套zk主要是因为新旧IGinX的元信息数据可能发生变化，比如上次UDF的修改就改了zk里的数据格式，所以只能把两个IGinX用的zk分开，这边最好还是分开比较好

2024-12-31 10:12 UTC, aqni commented on .github/workflows/tpc-h.yml
> +            - name: Run Metadata
clear data 不会清空元数据吗？

2025-01-02 10:36 UTC, aqni commented on .github/workflows/tpc-h.yml
> +            - name: Run Metadata
已经改成两个zk了

2025-01-06 05:09 UTC, shinyano approved these changes

2025-01-06 13:50 UTC, zhuyuqing requested changes

2025-01-06 13:50 UTC, zhuyuqing commented on test/src/test/resources/tpch/queries/q19.sql
> +    SUM( revenue ) AS revenue
这样改不合适吧，q19和q19a应当是原样，应当调整testConfgi.properties文件。

2025-01-07 10:09 UTC, shinyano commented on conf/config.properties
> +#storageEngineList=127.0.0.1#3306#relational#engine=mysql#username=root#has_data=false
这边作为样例为啥要删掉两个属性呢

2025-01-07 11:54 UTC, aqni commented on conf/config.properties
> +#storageEngineList=127.0.0.1#3306#relational#engine=mysql#username=root#has_data=false
目前这个样例已经不太符合当前代码了
- password=mysql 在 action mysql上默认无密码，而且上面 pg 已经有 password 的样例了。
- meta_properties_path=your-meta-properties-path，默认情况下 mysql 不需要配置meta_properties_path。

2025-01-10 01:15 UTC, merged