dev parallel Group By
IGinX-THU/IGinX pull request #63
Opened 2023-04-10 09:05 UTC by Cauchy-NY

2023-04-21 07:09 UTC, iznauy requested changes

2023-04-21 07:09 UTC, iznauy commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/GroupByLazyStream.java
> +    private final ReentrantReadWriteLock lock = new ReentrantReadWriteLock();
建议换成写锁

2023-04-21 07:09 UTC, iznauy commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/GroupByLazyStream.java
> +                                lock.writeLock().unlock();
可能会存在开启多个线程但是加速比率又比较低的情况。加锁部分执行时间可能会占大头。

2023-04-23 00:53 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/RowUtils.java
> +            groups = parallelBuild(table, colIndex);
这个方案是否更优会在后续的实验中验证

2023-04-23 00:53 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/GroupByLazyStream.java
> +                                lock.writeLock().unlock();
这个方案是否更优会在后续的实验中验证

2023-04-23 02:40 UTC, iznauy approved these changes

2023-04-23 03:21 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/GroupByLazyStream.java
> +        }
因为合并后会需要返回多值，合并不经济，目前先不合并——by一力

2023-04-23 03:21 UTC, zhuyuqing approved these changes

2023-04-23 03:22 UTC, merged