split special path test
IGinX-THU/IGinX pull request #76
Opened 2023-05-23 02:37 UTC by Cauchy-NY

2023-05-23 07:03 UTC, Cauchy-NY commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/tool/DBConf.java
> +    private static final Map<DBConfType, Boolean> DB_CONF_TYPE_MAP = new HashMap<>();
ok

2023-05-24 01:32 UTC, SolomonAnn approved these changes

2023-05-24 08:05 UTC, zhuyuqing requested changes

2023-05-24 08:05 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> +    public void testFileSystemSupportedSpecialPath() {
改名

2023-05-24 08:13 UTC, merged