feat(PostgreSQL): select pushdown for PostgreSQL
IGinX-THU/IGinX pull request #94
Opened 2023-06-16 13:37 UTC by Yihao-Xu

Query and dummy query with predicate pushdown are implemented

2023-07-28 03:22 UTC, SolomonAnn commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +  public static final String QUERY_STATEMENT_WITH_JOIN = "SELECT %s FROM %s WHERE %s ORDER BY %s;";
这条语句好像和JOIN没关系，命名是不是要改一下？

2023-07-28 03:23 UTC, SolomonAnn commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +      "SELECT concat(%s) AS " + KEY_NAME + ", %s FROM %s WHERE %s ORDER BY concat(%s);";
这一行后面加个空行

2023-07-28 03:29 UTC, SolomonAnn approved these changes

2023-07-28 07:25 UTC, Yihao-Xu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +      "SELECT concat(%s) AS " + KEY_NAME + ", %s FROM %s WHERE %s ORDER BY concat(%s);";
加了

2023-07-28 07:31 UTC, Yihao-Xu commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
> +  public static final String QUERY_STATEMENT_WITH_JOIN = "SELECT %s FROM %s WHERE %s ORDER BY %s;";
改成了QUERY_STATEMENT_WITHOUT_KEYNAME

2023-07-28 13:44 UTC, zhuyuqing requested changes

2023-07-28 13:44 UTC, zhuyuqing commented on dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
> +      // table中带有了通配符，将所有table都join到一起进行查询，以便输入filter.
感觉性能会很差啊，需要再进行一次性能测试，PR才能合

2023-08-11 03:08 UTC, zhuyuqing approved these changes

2023-08-11 03:09 UTC, merged